(function(g){var window=this;'use strict';var ZRa=function(a,b){return g.gc(a,b)},$Ra=function(a,b){b=b instanceof g.tf?b:g.zf(b,/^data:image\//i.test(b));
a.src=g.uf(b)},O6=function(a){g.Zj(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.Pa()).toString(36));
return a},P6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.ek(a.u,b,c)},aSa=function(a){if(a instanceof g.lo)return a;
if("function"==typeof a.Lg)return a.Lg(!1);if(g.Ka(a)){var b=0,c=new g.lo;c.sj=function(){for(;;){if(b>=a.length)throw g.$q;if(b in a)return a[b++];b++}};
return c}throw Error("Not implemented");},bSa=function(a,b,c){if(g.Ka(a))try{g.Qb(a,b,c)}catch(d){if(d!==g.$q)throw d;
}else{a=aSa(a);try{for(;;)b.call(c,a.sj(),void 0,a)}catch(d){if(d!==g.$q)throw d;}}},cSa=function(a,b){var c=[];
bSa(b,function(d){try{var e=g.Ar.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.zr(e)&&c.push(d)},a);
return c},dSa=function(a,b){cSa(a,b).forEach(function(c){g.Ar.prototype.remove.call(this,c)},a)},eSa=function(a){if(a.ma){if(a.ma.locationOverrideToken)return{locationOverrideToken:a.ma.locationOverrideToken};
if(null!=a.ma.latitudeE7&&null!=a.ma.longitudeE7)return{latitudeE7:a.ma.latitudeE7,longitudeE7:a.ma.longitudeE7}}return null},fSa=function(a,b){g.wb(a,b)||a.push(b)},Q6=function(a){var b=0,c;
for(c in a)b++;return b},gSa=function(a){try{return g.D.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},R6=function(a){if(g.D.JSON)try{return g.D.JSON.parse(a)}catch(b){}return gSa(a)},hSa=function(a,b,c,d){var e=new g.Rj(null,void 0);
a&&g.Sj(e,a);b&&g.Tj(e,b);c&&g.Uj(e,c);d&&(e.K=d);return e},S6=function(a,b){g.fv[a]=!0;
var c=g.dv();c&&c.publish.apply(c,arguments);g.fv[a]=!1},T6=function(a){this.name=this.id="";
this.clientName="UNKNOWN_INTERFACE";this.app="";this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.ar;this.model=this.brand="";this.year=0;this.chipset=this.osVersion=this.os="";this.mdxDialServerType="MDX_DIAL_SERVER_TYPE_UNKNOWN";a&&(this.id=a.id||a.name,this.name=a.name,this.clientName=a.clientName?a.clientName.toUpperCase():"UNKNOWN_INTERFACE",this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=
a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",iSa(this,a.capabilities||""),jSa(this,a.experiments||""),this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",this.osVersion=a.osVersion||"",this.chipset=a.chipset||"",this.mdxDialServerType=a.mdxDialServerType||"MDX_DIAL_SERVER_TYPE_UNKNOWN",a=a.deviceInfo)&&(a=JSON.parse(a),this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",
this.osVersion=a.osVersion||"",this.chipset=a.chipset||"",this.clientName=a.clientName?a.clientName.toUpperCase():"UNKNOWN_INTERFACE",this.mdxDialServerType=a.mdxDialServerType||"MDX_DIAL_SERVER_TYPE_UNKNOWN")},iSa=function(a,b){a.capabilities.clear();
g.Ko(b.split(","),g.Oa(ZRa,kSa)).forEach(function(c){a.capabilities.add(c)})},jSa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},U6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},V6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},lSa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},mSa=function(a){return new U6(a)},nSa=function(a){return Array.isArray(a)?g.ym(a,mSa):[]},W6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},X6=function(a){return Array.isArray(a)?"["+g.ym(a,W6).join(",")+"]":"null"},Y6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},oSa=function(a){return g.ym(a,function(b){return{key:b.id,
name:b.name}})},Z6=function(a,b){return g.tb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},$6=function(a,b){return g.tb(a,function(c){return V6(c,b)})},pSa=function(){var a=(0,g.Iz)();
a&&dSa(a,a.i.Lg(!0))},a7=function(){var a=g.Lz("yt-remote-connected-devices")||[];
g.Mb(a);return a},qSa=function(a){if(g.xb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.ym(a,function(d,e){return 0==e?d:d.substring(c.length)})},rSa=function(a){g.Kz("yt-remote-connected-devices",a,86400)},c7=function(){if(b7)return b7;
var a=g.Lz("yt-remote-device-id");a||(a=Y6(),g.Kz("yt-remote-device-id",a,31536E3));for(var b=a7(),c=1,d=a;g.wb(b,d);)c++,d=a+"#"+c;return b7=d},d7=function(){var a=a7(),b=c7();
g.wb(a,b);g.Nz()&&g.Pb(a,b);a=qSa(a);if(g.xb(a))try{g.Pt("remote_sid")}catch(c){}else try{g.Nt("remote_sid",a.join(","),-1)}catch(c){}},sSa=function(){return g.Lz("yt-remote-session-browser-channel")},tSa=function(){return g.Lz("yt-remote-local-screens")||[]},uSa=function(){g.Kz("yt-remote-lounge-token-expiration",!0,86400)},vSa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.ym(tSa(),function(d){return d.loungeToken}),c=g.ym(a,function(d){return d.loungeToken});
g.zm(c,function(d){return!g.wb(b,d)})&&uSa();
g.Kz("yt-remote-local-screens",a,31536E3)},wSa=function(a,b){g.Kz("yt-remote-session-browser-channel",a);
g.Kz("yt-remote-session-screen-id",b);a=a7();b=c7();g.wb(a,b)||a.push(b);rSa(a);d7()},e7=function(a){a||(g.Mz("yt-remote-session-screen-id"),g.Mz("yt-remote-session-video-id"));
d7();a=a7();g.Ab(a,c7());rSa(a)},xSa=function(){if(!f7){var a=g.Kr();
a&&(f7=new g.ur(a))}},ySa=function(){xSa();
return f7?!!f7.get("yt-remote-use-staging-server"):!1},g7=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?parseInt(a[1],10):0},zSa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},ASa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},h7=function(a){a.length?BSa(a.shift(),function(){h7(a)}):i7()},CSa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},BSa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.Zk(d,g.ir(a));(document.head||document.documentElement).appendChild(d)},DSa=function(){var a=g7(),b=[];
if(1<a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}return b},i7=function(){var a=ASa();
a&&a(!1,"No cast extension found")},j7=function(){if(ESa){var a=2,b=ASa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;BSa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",i7,c)}},FSa=function(){j7();
var a=DSa();a.push("//www.gstatic.com/eureka/clank/cast_sender.js");h7(a)},HSa=function(){j7();
var a=DSa();a.push.apply(a,g.v(GSa.map(CSa)));a.push("//www.gstatic.com/eureka/clank/cast_sender.js");h7(a)},k7=function(a,b,c){g.I.call(this);
this.J=null!=c?(0,g.E)(a,c):a;this.Vf=b;this.D=(0,g.E)(this.mQ,this);this.i=!1;this.u=0;this.B=this.Lb=null;this.C=[]},l7=function(a,b,c){g.I.call(this);
this.C=null!=c?a.bind(c):a;this.Vf=b;this.B=null;this.i=!1;this.u=0;this.Lb=null},m7=function(a){a.Lb=g.zh(function(){a.Lb=null;
a.i&&!a.u&&(a.i=!1,m7(a))},a.Vf);
var b=a.B;a.B=null;a.C.apply(null,b)},n7=function(){},o7=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.D.setTimeout(function(){a()},b)},q7=function(a){p7.dispatchEvent(new ISa(p7,a))},ISa=function(a,b){g.xe.call(this,"statevent",a);
this.stat=b},r7=function(a,b,c,d){this.i=a;
this.B=b;this.S=c;this.K=d||1;this.u=45E3;this.C=new g.fk(this);this.J=new g.yh;this.J.setInterval(250)},KSa=function(a,b,c){a.vt=1;
a.Pm=O6(b.clone());a.oq=c;a.D=!0;JSa(a,null)},s7=function(a,b,c,d,e){a.vt=1;
a.Pm=O6(b.clone());a.oq=null;a.D=c;e&&(a.GN=!1);JSa(a,d)},JSa=function(a,b){a.Us=Date.now();
t7(a);a.qo=a.Pm.clone();P6(a.qo,"t",a.K);a.qB=0;a.Nf=a.i.jD(a.i.ix()?b:null);0<a.fC&&(a.DA=new l7((0,g.E)(a.IO,a,a.Nf),a.fC));a.C.Qa(a.Nf,"readystatechange",a.nQ);b=a.Qo?g.pc(a.Qo):{};a.oq?(a.nB="POST",b["Content-Type"]="application/x-www-form-urlencoded",a.Nf.send(a.qo,a.nB,a.oq,b)):(a.nB="GET",a.GN&&!g.Bg&&(b.Connection="close"),a.Nf.send(a.qo,a.nB,null,b));a.i.tj(1)},MSa=function(a,b){var c=a.qB,d=b.indexOf("\n",c);
if(-1==d)return u7;c=Number(b.substring(c,d));if(isNaN(c))return LSa;d+=1;if(d+c>b.length)return u7;b=b.substr(d,c);a.qB=d+c;return b},OSa=function(a,b){a.Us=Date.now();
t7(a);var c=b?window.location.hostname:"";a.qo=a.Pm.clone();g.Zj(a.qo,"DOMAIN",c);g.Zj(a.qo,"t",a.K);try{a.Jj=new ActiveXObject("htmlfile")}catch(m){v7(a);a.Jm=7;q7(22);w7(a);return}var d="<html><body>";if(b){var e="";for(b=0;b<c.length;b++){var f=c.charAt(b);if("<"==f)f=e+"\\x3c";else if(">"==f)f=e+"\\x3e";else{if(f in x7)f=x7[f];else if(f in NSa)f=x7[f]=NSa[f];else{var h=f.charCodeAt(0);if(31<h&&127>h)var l=f;else{if(256>h){if(l="\\x",16>h||256<h)l+="0"}else l="\\u",4096>h&&(l+="0");l+=h.toString(16).toUpperCase()}f=
x7[f]=l}f=e+f}e=f}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.Qf(g.lf("b/12014412"),d);a.Jj.open();a.Jj.write(g.Mf(c));a.Jj.close();a.Jj.parentWindow.m=(0,g.E)(a.gW,a);a.Jj.parentWindow.d=(0,g.E)(a.RM,a,!0);a.Jj.parentWindow.rpcClose=(0,g.E)(a.RM,a,!1);c=a.Jj.createElement("DIV");a.Jj.parentWindow.document.body.appendChild(c);d=g.yf(a.qo.toString());d=g.hg(g.uf(d));d=g.Qf(g.lf("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Sf(c,d);a.i.tj(1)},t7=function(a){a.ZG=Date.now()+
a.u;
PSa(a,a.u)},PSa=function(a,b){if(null!=a.It)throw Error("WatchDog timer not null");
a.It=o7((0,g.E)(a.nW,a),b)},y7=function(a){a.It&&(g.D.clearTimeout(a.It),a.It=null)},w7=function(a){a.i.rf()||a.jp||a.i.Rx(a)},v7=function(a){y7(a);
g.ue(a.DA);a.DA=null;a.J.stop();g.hk(a.C);if(a.Nf){var b=a.Nf;a.Nf=null;b.abort();b.dispose()}a.Jj&&(a.Jj=null)},z7=function(a,b){try{a.i.JM(a,b),a.i.tj(4)}catch(c){}},RSa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;QSa(a,b,function(h){h?c(!0):g.D.setTimeout(function(){RSa(a,b,c,d,f)},f)})}},QSa=function(a,b,c){var d=new Image;
d.onload=function(){try{A7(d),c(!0)}catch(e){}};
d.onerror=function(){try{A7(d),c(!1)}catch(e){}};
d.onabort=function(){try{A7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{A7(d),c(!1)}catch(e){}};
g.D.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
$Ra(d,a)},A7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},SSa=function(a){this.i=a;
this.u=new n7},TSa=function(a){var b=B7(a.i,a.Ku,"/mail/images/cleardot.gif");
O6(b);RSa(b.toString(),5E3,(0,g.E)(a.eR,a),3,2E3);a.tj(1)},D7=function(a){var b=a.i.Z;
if(null!=b)q7(5),b?(q7(11),C7(a.i,a,!1)):(q7(12),C7(a.i,a,!0));else if(a.lh=new r7(a,void 0,void 0,void 0),a.lh.Qo=a.gC,b=a.i,b=B7(b,b.ix()?a.nu:null,a.hC),q7(5),!g.Qc||g.Jc(10))P6(b,"TYPE","xmlhttp"),s7(a.lh,b,!1,a.nu,!1);else{P6(b,"TYPE","html");var c=a.lh;a=!!a.nu;c.vt=3;c.Pm=O6(b.clone());OSa(c,a)}},E7=function(a,b,c){this.i=1;
this.u=[];this.C=[];this.D=new n7;this.S=a||null;this.Z=null!=b?b:null;this.J=c||!1},USa=function(a,b){this.i=a;
this.map=b;this.context=null},VSa=function(a,b,c,d){g.xe.call(this,"timingevent",a);
this.size=b;this.Ww=d},WSa=function(a){g.xe.call(this,"serverreachability",a)},ZSa=function(a){XSa(a);
if(3==a.i){var b=a.lw++,c=a.Ly.clone();g.Zj(c,"SID",a.B);g.Zj(c,"RID",b);g.Zj(c,"TYPE","terminate");F7(a,c);b=new r7(a,a.B,b,void 0);b.vt=2;b.Pm=O6(c.clone());$Ra(new Image,b.Pm.toString());b.Us=Date.now();t7(b)}YSa(a)},$Sa=function(a){a.ER(1,0);
a.Ly=B7(a,null,a.iC);G7(a)},XSa=function(a){a.Tm&&(a.Tm.abort(),a.Tm=null);
a.He&&(a.He.cancel(),a.He=null);a.Al&&(g.D.clearTimeout(a.Al),a.Al=null);H7(a);a.Vg&&(a.Vg.cancel(),a.Vg=null);a.hn&&(g.D.clearTimeout(a.hn),a.hn=null)},aTa=function(a,b){if(0==a.i)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new USa(a.iT++,b));2!=a.i&&3!=a.i||G7(a)},bTa=function(a){var b=0;
a.He&&b++;a.Vg&&b++;return b},G7=function(a){a.Vg||a.hn||(a.hn=o7((0,g.E)(a.PM,a),0),a.Pr=0)},dTa=function(a,b){if(1==a.i){if(!b){a.lw=Math.floor(1E5*Math.random());
b=a.lw++;var c=new r7(a,"",b,void 0);c.Qo=a.Vj;var d=I7(a),e=a.Ly.clone();g.Zj(e,"RID",b);g.Zj(e,"CVER","1");F7(a,e);KSa(c,e,d);a.Vg=c;a.i=2}}else 3==a.i&&(b?cTa(a,b):0==a.u.length||a.Vg||cTa(a))},cTa=function(a,b){if(b)if(6<a.kp){a.u=a.C.concat(a.u);
a.C.length=0;var c=a.lw-1;b=I7(a)}else c=b.S,b=b.oq;else c=a.lw++,b=I7(a);var d=a.Ly.clone();g.Zj(d,"SID",a.B);g.Zj(d,"RID",c);g.Zj(d,"AID",a.As);F7(a,d);c=new r7(a,a.B,c,a.Pr+1);c.Qo=a.Vj;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Vg=c;KSa(c,d,b)},F7=function(a,b){a.Of&&(a=a.Of.dK())&&g.Wb(a,function(c,d){g.Zj(b,d,c)})},I7=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.kp&&0<b){var d=a.u[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={Rq:e.Rq},f++){e.Rq=a.u[f].i;var h=a.u[f].map;e.Rq=6>=a.kp?f:e.Rq-d;try{g.Wb(h,function(l){return function(m,n){c.push("req"+l.Rq+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.Rq+"_type="+encodeURIComponent("_badmap"))}}a.C=a.C.concat(a.u.splice(0,b));
return c.join("&")},eTa=function(a){a.He||a.Al||(a.K=1,a.Al=o7((0,g.E)(a.OM,a),0),a.zr=0)},J7=function(a){if(a.He||a.Al||3<=a.zr)return!1;
a.K++;a.Al=o7((0,g.E)(a.OM,a),fTa(a,a.zr));a.zr++;return!0},C7=function(a,b,c){a.lB=c;
a.Wj=b.fl;a.J||$Sa(a)},H7=function(a){null!=a.vp&&(g.D.clearTimeout(a.vp),a.vp=null)},fTa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},K7=function(a,b){if(2==b||9==b){var c=null;
a.Of&&(c=null);var d=(0,g.E)(a.qX,a);c||(c=new g.Rj("//www.google.com/images/cleardot.gif"),O6(c));QSa(c.toString(),1E4,d)}else q7(2);gTa(a,b)},gTa=function(a,b){a.i=0;
a.Of&&a.Of.rJ(b);YSa(a);XSa(a)},YSa=function(a){a.i=0;
a.Wj=-1;if(a.Of)if(0==a.C.length&&0==a.u.length)a.Of.WC();else{g.Db(a.C);var b=g.Db(a.u);a.C.length=0;a.u.length=0;a.Of.WC(b)}},B7=function(a,b,c){var d=g.ak(c);
if(""!=d.i)b&&g.Tj(d,b+"."+d.i),g.Uj(d,d.B);else{var e=window.location;d=hSa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.qv&&g.Wb(a.qv,function(f,h){g.Zj(d,h,f)});
g.Zj(d,"VER",a.kp);F7(a,d);return d},hTa=function(){},iTa=function(){this.i=[];
this.u=[]},jTa=function(a,b){this.action=a;
this.params=b||{}},L7=function(a,b){g.I.call(this);
this.i=new g.M(this.XV,0,this);g.J(this,this.i);this.Vf=5E3;this.u=0;if("function"===typeof a)b&&(a=(0,g.E)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.E)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},M7=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.ya=a;this.J=b;this.B=new g.tr;this.u=new L7(this.UW,this);this.i=null;this.Y=!1;this.D=null;this.Z="";this.S=this.C=0;this.K=[];this.Aa=c;this.ma=d;this.Ea=e},kTa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.lB,sessionId:a.i.B,arrayId:a.i.As}},lTa=function(a,b){a.S=b||0;
a.u.stop();N7(a);a.i&&(3==a.i.getState()&&dTa(a.i),ZSa(a.i));a.S=0},O7=function(a){return!!a.i&&3==a.i.getState()},N7=function(a){if(a.i){var b=a.ma(),c=a.i.Vj||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.Vj=c}},P7=function(a){this.port=this.domain="";
this.i="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.hi(4,a))||"";b&&(this.port=":"+b);this.domain=g.ii(a)||"";a=g.Ub;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.nb(a,"10.0")&&(this.u=!1))},Q7=function(a,b){var c=a.i;
a.u&&(c="https://"+a.domain+a.port+a.i);return g.ti(c+b,{})},R7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Oa(a.C,d,!0),onError:g.Oa(a.B,e),onTimeout:g.Oa(a.D,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Ct(b,a)},pTa=function(){var a=mTa;
nTa();S7.push(a);oTa()},T7=function(a,b){nTa();
var c=qTa(a,String(b));g.xb(S7)?rTa(c):(oTa(),g.Qb(S7,function(d){d(c)}))},nTa=function(){S7||(S7=g.Ga("yt.mdx.remote.debug.handlers_")||[],g.Fa("yt.mdx.remote.debug.handlers_",S7,void 0))},rTa=function(a){var b=(U7+1)%50;
U7=b;V7[b]=a;W7||(W7=49==b)},oTa=function(){var a=S7;
if(V7[0]){var b=W7?U7:-1;do{b=(b+1)%50;var c=V7[b];g.Qb(a,function(d){d(c)})}while(b!=U7);
V7=Array(50);U7=-1;W7=!1}},qTa=function(a,b){var c=(Date.now()-sTa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},X7=function(a){g.R.call(this);
this.J=a;this.screens=[]},tTa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c)return a=c.name,c.id=b.id||c.id,c.name=b.name,c.token=b.token,c.uuid=b.uuid||c.uuid,c.name!=a;a.screens.push(b);return!0},uTa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Ko(a.screens,function(f){return!!Z6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=tTa(a,b[d])||c;return c},vTa=function(a,b){var c=a.screens.length;
a.screens=g.Ko(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},Y7=function(a,b,c,d,e){g.R.call(this);
this.B=a;this.K=b;this.C=c;this.J=d;this.D=e;this.u=0;this.i=null;this.Lb=NaN},$7=function(a){X7.call(this,"LocalScreenService");
this.u=a;this.i=NaN;Z7(this);this.info("Initializing with "+X6(this.screens))},wTa=function(a){if(a.screens.length){var b=g.ym(a.screens,function(d){return d.id}),c=Q7(a.u,"/pairing/get_lounge_token_batch");
R7(a.u,c,{screen_ids:b.join(",")},(0,g.E)(a.aS,a),(0,g.E)(a.ZR,a))}},Z7=function(a){if(g.Cs("deprecate_pair_servlet_enabled"))return uTa(a,[]);
var b=nSa(tSa());b=g.Ko(b,function(c){return!c.uuid});
return uTa(a,b)},a8=function(a,b){vSa(g.ym(a.screens,lSa));
b&&uSa()},c8=function(a,b){g.R.call(this);
this.J=b;b=(b=g.Lz("yt-remote-online-screen-ids")||"")?b.split(","):[];for(var c={},d=this.J(),e=0,f=d.length;e<f;++e){var h=d[e].id;c[h]=g.wb(b,h)}this.i=c;this.D=a;this.B=this.C=NaN;this.u=null;b8("Initialized with "+g.Zh(this.i))},d8=function(a,b,c){var d=Q7(a.D,"/pairing/get_screen_availability");
R7(a.D,d,{lounge_token:b.token},(0,g.E)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.E)(function(){c(!1)},a))},e8=function(a,b){a:if(Q6(b)!=Q6(a.i))var c=!1;
else{c=g.ec(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(b8("Updated online screens: "+g.Zh(a.i)),a.i=b,a.ea("screenChange"));xTa(a)},f8=function(a){isNaN(a.B)||g.wt(a.B);
a.B=g.ut((0,g.E)(a.QF,a),0<a.C&&a.C<g.Pa()?2E4:1E4)},b8=function(a){T7("OnlineScreenService",a)},yTa=function(a){var b={};
g.Qb(a.J(),function(c){c.token?b[c.token]=c.id:this.me("Requesting availability of screen w/o lounge token.")});
return b},xTa=function(a){a=g.ec(g.Xb(a.i,function(b){return b}));
g.Mb(a);a.length?g.Kz("yt-remote-online-screen-ids",a.join(","),60):g.Mz("yt-remote-online-screen-ids")},g8=function(a,b){b=void 0===b?!1:b;
X7.call(this,"ScreenService");this.C=a;this.K=b;this.i=this.u=null;this.B=[];this.D={};zTa(this)},BTa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var h=a.Fh(),l=c?$6(h,c):null;c&&(a.K||l)||(l=$6(h,b));if(l){l.uuid=b;var m=h8(a,l);d8(a.i,m,function(n){e(n?m:null)})}else c?ATa(a,c,(0,g.E)(function(n){var p=h8(this,new U6({name:d,
screenId:c,loungeToken:n,dialId:b||""}));d8(this.i,p,function(q){e(q?p:null)})},a),f):e(null)},CTa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},DTa=function(a,b,c){d8(a.i,b,c)},ATa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){f=h&&h.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Ct(Q7(a.C,"/pairing/get_lounge_token_batch"),e)},ETa=function(a){a.screens=a.u.Fh();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+X6(a.screens))},zTa=function(a){i8(a);
a.u=new $7(a.C);a.u.subscribe("screenChange",(0,g.E)(a.jS,a));ETa(a);a.K||(a.B=nSa(g.Lz("yt-remote-automatic-screen-cache")||[]));i8(a);a.info("Initializing automatic screens: "+X6(a.B));a.i=new c8(a.C,(0,g.E)(a.Fh,a,!0));a.i.subscribe("screenChange",(0,g.E)(function(){this.ea("onlineScreenChange")},a))},h8=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=$6(a.B,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.B.push(b),a.K||FTa(a));i8(a);a.D[b.uuid]=b.id;g.Kz("yt-remote-device-id-map",a.D,31536E3);return b},FTa=function(a){a=g.Ko(a.B,function(b){return"shortLived"!=b.idType});
g.Kz("yt-remote-automatic-screen-cache",g.ym(a,lSa))},i8=function(a){a.D=g.Lz("yt-remote-device-id-map")||{}},j8=function(a,b,c){g.R.call(this);
this.Ea=c;this.B=a;this.i=b;this.C=null},k8=function(a,b){a.C=b;
a.ea("sessionScreen",a.C)},GTa=function(a,b){a.C&&(a.C.token=b,h8(a.B,a.C));
a.ea("sessionScreen",a.C)},l8=function(a,b){T7(a.Ea,b)},m8=function(a,b,c){j8.call(this,a,b,"CastSession");
var d=this;this.config_=c;this.u=null;this.ma=(0,g.E)(this.sQ,this);this.Aa=(0,g.E)(this.rW,this);this.Y=g.ut(function(){HTa(d,null)},12E4);
this.K=this.D=this.J=this.S=0;this.ya=!1;this.Z="unknown"},n8=function(a,b){g.wt(a.K);
a.K=0;0==b?ITa(a):a.K=g.ut(function(){ITa(a)},b)},ITa=function(a){JTa(a,"getLoungeToken");
g.wt(a.D);a.D=g.ut(function(){KTa(a,null)},3E4)},JTa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.Zh(void 0));
var c={};c.type=b;a.u?a.u.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ha,(0,g.E)(function(){l8(this,"Failed to send message: "+b+".")},a)):l8(a,"Sending yt message without session: "+g.Zh(c))},o8=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.rK(b,function(c){k8(a,c)},function(){return a.zg()},5)):a.zg(Error("Waiting for session status timed out."))},MTa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new U6(b);LTa(a,d,function(e){e?(a.ya=!0,h8(a.B,d),k8(a,d),a.Z="unknown",n8(a,c)):(g.Gs(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.zg())},5)},HTa=function(a,b){g.wt(a.Y);
a.Y=0;b?a.config_.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?MTa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.Gs(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),o8(a,b.screenId))):(g.Gs(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+
".")),o8(a,b.screenId)):o8(a,b.screenId):a.zg(Error("Waiting for session status timed out."))},KTa=function(a,b){g.wt(a.D);
a.D=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.Z=c,n8(a,3E4)):(GTa(a,b.loungeToken),a.ya=!1,a.Z="unknown",n8(a,b.loungeTokenRefreshIntervalMs))},LTa=function(a,b,c,d){g.wt(a.J);
a.J=0;DTa(a.B,b,function(e){e||0>d?c(e):a.J=g.ut(function(){LTa(a,b,c,d-1)},300)})},NTa=function(a){g.wt(a.S);
a.S=0;g.wt(a.J);a.J=0;g.wt(a.Y);a.Y=0;g.wt(a.D);a.D=0;g.wt(a.K);a.K=0},p8=function(a,b,c,d){j8.call(this,a,b,"DialSession");
this.config_=d;this.u=this.S=null;this.Aa="";this.La=c;this.Ja=null;this.Y=g.Ha;this.Z=NaN;this.Ka=(0,g.E)(this.tQ,this);this.D=g.Ha;this.K=this.J=0;this.ma=!1;this.ya="unknown"},q8=function(a){var b;
return!!(a.config_.enableDialLoungeToken&&(null==(b=a.u)?0:b.getDialAppInfo))},OTa=function(a){a.D=a.B.ZH(a.Aa,a.i.label,a.i.friendlyName,q8(a),function(b,c){a.D=g.Ha;
a.ma=!0;k8(a,b);"shortLived"==b.idType&&0<c&&r8(a,c)},function(b){a.D=g.Ha;
a.zg(b)})},PTa=function(a){var b={};
b.pairingCode=a.Aa;b.theme=a.La;ySa()&&(b.env_useStageMdx=1);return g.ri(b)},s8=function(a){return new Promise(function(b){a.Aa=Y6();
if(a.Ja){var c=new chrome.cast.DialLaunchResponse(!0,PTa(a));b(c);OTa(a)}else a.Y=function(){g.wt(a.Z);a.Y=function(){};
a.Z=NaN;var d=new chrome.cast.DialLaunchResponse(!0,PTa(a));b(d);OTa(a)},a.Z=g.ut(function(){a.Y()},100)})},RTa=function(a,b,c){a.info("initOnConnectedScreenDataPromise_: Received screenData: "+JSON.stringify(b));
var d=new U6(b);return(new Promise(function(e){QTa(a,d,function(f){f?(a.ma=!0,h8(a.B,d),k8(a,d),r8(a,c)):g.Gs(Error("DialSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online."));e(f)},5)})).then(function(e){return e?new chrome.cast.DialLaunchResponse(!1):s8(a)})},STa=function(a,b){var c=a.S.receiver.label,d=a.i.friendlyName;
return(new Promise(function(e){BTa(a.B,c,b,d,function(f){f&&f.token&&k8(a,f);e(f)},function(f){l8(a,"Failed to get DIAL screen: "+f);
e(null)})})).then(function(e){return e&&e.token?new chrome.cast.DialLaunchResponse(!1):s8(a)})},QTa=function(a,b,c,d){g.wt(a.J);
a.J=0;DTa(a.B,b,function(e){e||0>d?c(e):a.J=g.ut(function(){QTa(a,b,c,d-1)},300)})},r8=function(a,b){a.info("getDialAppInfoWithTimeout_ "+b);
q8(a)&&(g.wt(a.K),a.K=0,0==b?TTa(a):a.K=g.ut(function(){TTa(a)},b))},TTa=function(a){q8(a)&&a.u.getDialAppInfo(function(b){a.info("getDialAppInfo dialLaunchData: "+JSON.stringify(b));
b=b.extraData||{};var c=null;if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";c?(a.ya=c,r8(a,3E4)):(a.ma=!1,a.ya="unknown",GTa(a,b.loungeToken),r8(a,b.loungeTokenRefreshIntervalMs))},function(b){a.info("getDialAppInfo error: "+b);
a.ya="noLoungeTokenResponse";r8(a,3E4)})},UTa=function(a){g.wt(a.J);
a.J=0;g.wt(a.K);a.K=0;a.D();a.D=function(){};
g.wt(a.Z)},t8=function(a,b){j8.call(this,a,b,"ManualSession");
this.u=g.ut((0,g.E)(this.Bs,this,null),150)},u8=function(a,b){g.R.call(this);
this.config_=b;this.u=a;this.S=b.appId||"233637DE";this.C=b.theme||"cl";this.Z=b.disableCastApi||!1;this.J=b.forceMirroring||!1;this.i=null;this.K=!1;this.B=[];this.D=(0,g.E)(this.kV,this)},VTa=function(a,b){return b?g.tb(a.B,function(c){return V6(b,c.label)},a):null},v8=function(a){T7("Controller",a)},mTa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},w8=function(a){return a.K||!!a.B.length||!!a.i},x8=function(a,b,c){b!=a.i&&(g.ue(a.i),(a.i=b)?(c?a.ea("yt-remote-cast2-receiver-resumed",
b.i):a.ea("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.E)(a.MM,a,b)),b.subscribe("sessionFailed",function(){return WTa(a,b)}),b.getScreen()?a.ea("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.Bs(null)):a.ea("yt-remote-cast2-session-change",null))},WTa=function(a,b){a.i==b&&a.ea("yt-remote-cast2-session-failed")},XTa=function(a){var b=a.u.YH(),c=a.i&&a.i.i;
a=g.ym(b,function(d){c&&V6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=VTa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},bUa=function(a,b,c,d){d.disableCastApi?y8("Cannot initialize because disabled by Mdx config."):YTa()?ZTa(b,d)&&(z8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?$Ta(a,c):(window.__onGCastApiAvailable=function(e,f){e?$Ta(a,c):(A8("Failed to load cast API: "+f),B8(!1),z8(!1),g.Mz("yt-remote-cast-available"),g.Mz("yt-remote-cast-receiver"),
aUa(),c(!1))},d.loadCastApiSetupScript?g.Oz("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?60<=g7()&&FSa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?i7():89<=g7()?HSa():(j7(),h7(GSa.map(CSa))))):y8("Cannot initialize because not running Chrome")},aUa=function(){y8("dispose");
var a=C8();a&&a.dispose();g.Fa("yt.mdx.remote.cloudview.instance_",null,void 0);cUa(!1);g.iv(D8);D8.length=0},E8=function(){return!!g.Lz("yt-remote-cast-installed")},dUa=function(){var a=g.Lz("yt-remote-cast-receiver");
return a?a.friendlyName:null},eUa=function(){y8("clearCurrentReceiver");
g.Mz("yt-remote-cast-receiver")},fUa=function(){return E8()?C8()?C8().getCastSession():(A8("getCastSelector: Cast is not initialized."),null):(A8("getCastSelector: Cast API is not installed!"),null)},G8=function(){E8()?C8()?F8()?(y8("Requesting cast selector."),C8().requestSession()):(y8("Wait for cast API to be ready to request the session."),D8.push(g.hv("yt-remote-cast2-api-ready",G8))):A8("requestCastSelector: Cast is not initialized."):A8("requestCastSelector: Cast API is not installed!")},H8=
function(a,b){F8()?C8().setConnectedScreenStatus(a,b):A8("setConnectedScreenStatus called before ready.")},YTa=function(){var a=0<=g.Ub.search(/ (CrMo|Chrome|CriOS)\//);
return g.ej||a},gUa=function(a,b){C8().init(a,b)},ZTa=function(a,b){var c=!1;
C8()||(a=new u8(a,b),a.subscribe("yt-remote-cast2-availability-change",function(d){g.Kz("yt-remote-cast-available",d);S6("yt-remote-cast2-availability-change",d)}),a.subscribe("yt-remote-cast2-receiver-selected",function(d){y8("onReceiverSelected: "+d.friendlyName);
g.Kz("yt-remote-cast-receiver",d);S6("yt-remote-cast2-receiver-selected",d)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(d){y8("onReceiverResumed: "+d.friendlyName);
g.Kz("yt-remote-cast-receiver",d);S6("yt-remote-cast2-receiver-resumed",d)}),a.subscribe("yt-remote-cast2-session-change",function(d){y8("onSessionChange: "+W6(d));
d||g.Mz("yt-remote-cast-receiver");S6("yt-remote-cast2-session-change",d)}),g.Fa("yt.mdx.remote.cloudview.instance_",a,void 0),c=!0);
y8("cloudview.createSingleton_: "+c);return c},C8=function(){return g.Ga("yt.mdx.remote.cloudview.instance_")},$Ta=function(a,b){B8(!0);
z8(!1);gUa(a,function(c){c?(cUa(!0),g.jv("yt-remote-cast2-api-ready")):(A8("Failed to initialize cast API."),B8(!1),g.Mz("yt-remote-cast-available"),g.Mz("yt-remote-cast-receiver"),aUa());b(c)})},y8=function(a){T7("cloudview",a)},A8=function(a){T7("cloudview",a)},B8=function(a){y8("setCastInstalled_ "+a);
g.Kz("yt-remote-cast-installed",a)},F8=function(){return!!g.Ga("yt.mdx.remote.cloudview.apiReady_")},cUa=function(a){y8("setApiReady_ "+a);
g.Fa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},z8=function(a){g.Fa("yt.mdx.remote.cloudview.initializing_",a,void 0)},I8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.J=this.K=0;this.trackData=null;this.hasNext=this.Ak=!1;this.S=this.D=this.i=this.C=0;this.B=NaN;this.u=!1;this.reset(a)},J8=function(a){a.audioTrackId=null;
a.trackData=null;a.playerState=-1;a.Ak=!1;a.hasNext=!1;a.K=0;a.J=g.Pa();a.C=0;a.i=0;a.D=0;a.S=0;a.B=NaN;a.u=!1},K8=function(a){return a.Ec()?(g.Pa()-a.J)/1E3:0},L8=function(a,b){a.K=b;
a.J=g.Pa()},M8=function(a){switch(a.playerState){case 1:case 1081:return(g.Pa()-a.J)/1E3+a.K;
case -1E3:return 0}return a.K},N8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&J8(a)},O8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.qc(a.trackData);b.hasPrevious=a.Ak;b.hasNext=a.hasNext;b.playerTime=a.K;b.playerTimeAt=a.J;b.seekableStart=a.C;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.S;b.liveIngestionTime=a.B;return b},Q8=function(a,b){g.R.call(this);
this.B=0;this.C=a;this.J=[];this.D=new iTa;this.u=this.i=null;this.Z=(0,g.E)(this.RT,this);this.K=(0,g.E)(this.ww,this);this.S=(0,g.E)(this.QT,this);this.Y=(0,g.E)(this.aU,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.gG,this),hUa(this))):c=3;0!=c&&(b?this.gG(c):g.ut((0,g.E)(function(){this.gG(c)},this),0));
(a=fUa())&&P8(this,a);this.subscribe("yt-remote-cast2-session-change",this.Y)},R8=function(a){return new I8(a.C.getPlayerContextData())},hUa=function(a){g.Qb("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange multiStateLoopEnabled loopModeChange".split(" "),function(b){this.J.push(this.C.subscribe(b,g.Oa(this.iV,b),this))},a)},iUa=function(a){g.Qb(a.J,function(b){this.C.unsubscribeByKey(b)},a);
a.J.length=0},S8=function(a){return 1==a.getState()},T8=function(a,b){var c=a.D;
50>c.i.length+c.u.length&&a.D.u.push(b)},V8=function(a,b,c){var d=R8(a);
L8(d,c);-1E3!=d.playerState&&(d.playerState=b);U8(a,d)},W8=function(a,b,c){a.C.sendMessage(b,c)},U8=function(a,b){iUa(a);
a.C.setPlayerContextData(O8(b));hUa(a)},P8=function(a,b){a.u&&(a.u.removeUpdateListener(a.Z),a.u.removeMediaListener(a.K),a.ww(null));
a.u=b;a.u&&(T7("CP","Setting cast session: "+a.u.sessionId),a.u.addUpdateListener(a.Z),a.u.addMediaListener(a.K),a.u.media.length&&a.ww(a.u.media[0]))},jUa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=R8(a);b.contentId!=d.videoId&&T7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;L8(d,a.i.getEstimatedTime());U8(a,d)}else T7("CP","No cast media video. Ignoring state update.")},X8=function(a,b,c){return(0,g.E)(function(d){this.me("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.me("Retrying "+b+" using MDx browser channel."),W8(this,b,c))},a)},Y8=function(a,b,c,d){d=void 0===d?!1:d;
g.R.call(this);this.D=NaN;this.ya=!1;this.S=this.K=this.Y=this.ma=NaN;this.Z=[];this.C=this.J=this.B=this.hc=this.i=null;this.Ka=a;this.Ea=d;this.Z.push(g.Au(window,"beforeunload",(0,g.E)(this.VR,this)));this.u=[];this.hc=new I8;this.Ja=b.id;this.Aa=b.idType;this.i=kUa(this,c);this.i.subscribe("handlerOpened",this.VT,this);this.i.subscribe("handlerClosed",this.ST,this);this.i.subscribe("handlerError",this.TT,this);this.i.subscribe("handlerMessage",this.UT,this);this.i.PA(b.token);this.subscribe("remoteQueueChange",
function(){var e=this.hc.videoId;g.Nz()&&g.Kz("yt-remote-session-video-id",e)},this)},lUa=function(a){return g.tb(a.u,function(b){return"LOUNGE_SCREEN"==b.type})},Z8=function(a){T7("conn",a)},kUa=function(a,b){return new M7(Q7(a.Ka,"/bc"),b,!1,function(){return a.dI()},"shortLived"==a.Aa)},$8=function(a,b){a.ea("proxyStateChange",b)},mUa=function(a){a.D=g.ut((0,g.E)(function(){Z8("Connecting timeout");
this.Lr(1)},a),2E4)},a9=function(a){g.wt(a.D);
a.D=NaN},b9=function(a){g.wt(a.ma);
a.ma=NaN},nUa=function(a){c9(a);
a.Y=g.ut((0,g.E)(function(){d9(this,"getNowPlaying")},a),2E4)},c9=function(a){g.wt(a.Y);
a.Y=NaN},pUa=function(a,b){var c=null;
if(b){var d=lUa(a);d&&(c={clientName:d.clientName,deviceMake:d.brand,deviceModel:d.model,osVersion:d.osVersion})}g.Fa("yt.mdx.remote.remoteClient_",c,void 0);b&&(a9(a),b9(a));c=O7(a.i)&&isNaN(a.D);b==c?b&&($8(a,1),d9(a,"getSubtitlesTrack")):b?(a.qK()&&a.hc.reset(),$8(a,1),d9(a,"getNowPlaying"),oUa(a)):a.Lr(1)},qUa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.hc.videoId&&(g.lc(b.params)?a.hc.trackData=null:a.hc.trackData=b.params,a.ea("remotePlayerChange"))},rUa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.hc.listId=b.params.listId||a.hc.listId;N8(a.hc,c,d);a.ea("remoteQueueChange")},tUa=function(a,b){b.params=b.params||{};
rUa(a,b);sUa(a,b);a.ea("autoplayDismissed")},sUa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
L8(a.hc,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.hc.playerState&&(c=-1E3);a.hc.playerState=c;c=Number(b.params.loadedTime);a.hc.S=isNaN(c)?0:c;a.hc.Ej(Number(b.params.duration));c=a.hc;var d=Number(b.params.liveIngestionTime);c.B=d;c.u=isNaN(d)?!1:!0;c=a.hc;d=Number(b.params.seekableStartTime);b=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.i=isNaN(b)?0:b;1==a.hc.playerState?nUa(a):c9(a);a.ea("remotePlayerChange")},uUa=function(a,b){if(-1E3!=a.hc.playerState){var c=
1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.hc.playerState=c;b=parseInt(b.params.currentTime,10);L8(a.hc,isNaN(b)?0:b);a.ea("remotePlayerChange")}},vUa=function(a,b){var c="true"==b.params.muted;
a.hc.volume=parseInt(b.params.volume,10);a.hc.muted=c;a.ea("remotePlayerChange")},wUa=function(a,b){a.J=b.params.videoId;
a.ea("nowAutoplaying",parseInt(b.params.timeout,10))},xUa=function(a,b){var c="true"==b.params.hasNext;
a.hc.Ak="true"==b.params.hasPrevious;a.hc.hasNext=c;a.ea("previousNextChange")},oUa=function(a){g.wt(a.S);
a.S=g.ut((0,g.E)(a.Lr,a,1),864E5)},d9=function(a,b,c){c?Z8("Sending: action="+b+", params="+g.Zh(c)):Z8("Sending: action="+b);
a.i.sendMessage(b,c)},e9=function(a){X7.call(this,"ScreenServiceProxy");
this.Qe=a;this.i=[];this.i.push(this.Qe.$_s("screenChange",(0,g.E)(this.xQ,this)));this.i.push(this.Qe.$_s("onlineScreenChange",(0,g.E)(this.PU,this)))},BUa=function(a,b){xSa();
if(!f7||!f7.get("yt-remote-disable-remote-module-for-dev")){b=g.P("MDX_CONFIG")||b;pSa();d7();f9||(f9=new P7(b?b.loungeApiHost:void 0),ySa()&&(f9.i="/api/loungedev"));g9||(g9=g.Ga("yt.mdx.remote.deferredProxies_")||[],g.Fa("yt.mdx.remote.deferredProxies_",g9,void 0));yUa();var c=h9();if(!c){var d=new g8(f9,b?b.disableAutomaticScreenCache||!1:!1);g.Fa("yt.mdx.remote.screenService_",d,void 0);c=h9();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,
disableCastApi:b.disableCastApi,enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken,forceMirroring:b.forceMirroring});g.Fa("yt.mdx.remote.enableConnectWithInitialState_",b?b.enableConnectWithInitialState||!1:!1,void 0);bUa(a,d,function(f){f?i9()&&H8(i9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){S6("yt-remote-receiver-availability-change")})},e)}b&&!g.Ga("yt.mdx.remote.initialized_")&&(g.Fa("yt.mdx.remote.initialized_",!0,void 0),j9("Initializing: "+
g.Zh(b)),k9.push(g.hv("yt-remote-cast2-api-ready",function(){S6("yt-remote-api-ready")})),k9.push(g.hv("yt-remote-cast2-availability-change",function(){S6("yt-remote-receiver-availability-change")})),k9.push(g.hv("yt-remote-cast2-receiver-selected",function(){l9(null);
S6("yt-remote-auto-connect","cast-selector-receiver")})),k9.push(g.hv("yt-remote-cast2-receiver-resumed",function(){S6("yt-remote-receiver-resumed","cast-selector-receiver")})),k9.push(g.hv("yt-remote-cast2-session-change",zUa)),k9.push(g.hv("yt-remote-connection-change",function(f){f?H8(i9(),"YouTube TV"):m9()||(H8(null,null),eUa())})),k9.push(g.hv("yt-remote-cast2-session-failed",function(){S6("yt-remote-connection-failed")})),a=n9(),b.isAuto&&(a.id+="#dial"),e=b.capabilities||[],g.Cs("desktop_enable_autoplay")&&
e.push("atp"),0<e.length&&(a.capabilities=e),a.name=b.device,a.app=b.app,(b=b.theme)&&(a.theme=b),j9(" -- with channel params: "+g.Zh(a)),a?(g.Kz("yt-remote-session-app",a.app),g.Kz("yt-remote-session-name",a.name)):(g.Mz("yt-remote-session-app"),g.Mz("yt-remote-session-name")),g.Fa("yt.mdx.remote.channelParams_",a,void 0),c.start(),i9()||AUa())}},CUa=function(){var a=h9().Qe.$_gos();
var b=o9();b&&p9()&&(Z6(a,b)||a.push(b));return oSa(a)},q9=function(){var a=DUa();
!a&&E8()&&dUa()&&(a={key:"cast-selector-receiver",name:dUa()});return a},DUa=function(){var a=CUa(),b=o9();
b||(b=m9());return g.tb(a,function(c){return b&&V6(b,c.key)?!0:!1})},o9=function(){var a=i9();
if(!a)return null;var b=h9().Fh();return $6(b,a)},zUa=function(a){j9("remote.onCastSessionChange_: "+W6(a));
if(a){var b=o9();if(b&&b.id==a.id){if(H8(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))r9&&(r9.token=a),(b=p9())&&b.PA(a)}else b&&s9(),t9(a,1)}else p9()&&s9()},s9=function(){F8()?C8().stopSession():A8("stopSession called before API ready.");
var a=p9();a&&(a.disconnect(1),u9(null))},v9=function(){var a=p9();
return!!a&&3!=a.getProxyState()},j9=function(a){T7("remote",a)},h9=function(){if(!w9){var a=g.Ga("yt.mdx.remote.screenService_");
w9=a?new e9(a):null}return w9},i9=function(){return g.Ga("yt.mdx.remote.currentScreenId_")},EUa=function(a){g.Fa("yt.mdx.remote.currentScreenId_",a,void 0)},FUa=function(){return g.Ga("yt.mdx.remote.connectData_")},l9=function(a){g.Fa("yt.mdx.remote.connectData_",a,void 0)},p9=function(){return g.Ga("yt.mdx.remote.connection_")},u9=function(a){var b=p9();
l9(null);a||EUa("");g.Fa("yt.mdx.remote.connection_",a,void 0);g9&&(g.Qb(g9,function(c){c(a)}),g9.length=0);
b&&!a?S6("yt-remote-connection-change",!1):!b&&a&&S6("yt-remote-connection-change",!0)},m9=function(){var a=g.Nz();
if(!a)return null;var b=h9();if(!b)return null;b=b.Fh();return $6(b,a)},t9=function(a,b){i9();
o9()&&o9();if(x9)r9=a;else{EUa(a.id);var c=g.Ga("yt.mdx.remote.enableConnectWithInitialState_")||!1;a=new Y8(f9,a,n9(),c);a.connect(b,FUa());a.subscribe("beforeDisconnect",function(d){S6("yt-remote-before-disconnect",d)});
a.subscribe("beforeDispose",function(){p9()&&(p9(),u9(null))});
a.subscribe("browserChannelAuthError",function(){var d=o9();d&&"shortLived"==d.idType&&(F8()?C8().handleBrowserChannelAuthError():A8("refreshLoungeToken called before API ready."))});
u9(a)}},AUa=function(){var a=m9();
a?(j9("Resume connection to: "+W6(a)),t9(a,0)):(e7(),eUa(),j9("Skipping connecting because no session screen found."))},yUa=function(){var a=n9();
if(g.lc(a)){a=c7();var b=g.Lz("yt-remote-session-name")||"",c=g.Lz("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Fa("yt.mdx.remote.channelParams_",a,void 0)}},n9=function(){return g.Ga("yt.mdx.remote.channelParams_")||{}},y9=function(a,b,c){g.I.call(this);
var d=this;this.u=a;this.I=b;this.Tb=c;this.events=new g.uD(this);this.Y=this.events.T(this.I,"onVolumeChange",function(e){GUa(d,e)});
this.D=!1;this.J=new g.SJ(64);this.i=new g.M(this.RN,500,this);this.B=new g.M(this.SN,1E3,this);this.S=new k7(this.GX,0,this);this.C={};this.Z=new g.M(this.AO,1E3,this);this.K=new l7(this.seekTo,1E3,this);this.ma=g.Ha;g.J(this,this.events);this.events.T(b,"onCaptionsTrackListChanged",this.AU);this.events.T(b,"captionschanged",this.OT);this.events.T(b,"captionssettingschanged",this.YN);this.events.T(b,"videoplayerreset",this.iA);this.events.T(b,"mdxautoplaycancel",function(){d.Tb.NJ()});
a=this.Tb;a.isDisposed();a.subscribe("proxyStateChange",this.IM,this);a.subscribe("remotePlayerChange",this.Aw,this);a.subscribe("remoteQueueChange",this.iA,this);a.subscribe("previousNextChange",this.FM,this);a.subscribe("nowAutoplaying",this.zM,this);a.subscribe("autoplayDismissed",this.cM,this);g.J(this,this.i);g.J(this,this.B);g.J(this,this.S);g.J(this,this.Z);g.J(this,this.K);this.YN();this.iA();this.Aw()},GUa=function(a,b){if(z9(a)){a.Tb.unsubscribe("remotePlayerChange",a.Aw,a);
var c=Math.round(b.volume);b=!!b.muted;var d=R8(a.Tb);if(c!==d.volume||b!==d.muted)a.Tb.setVolume(c,b),a.Z.start();a.Tb.subscribe("remotePlayerChange",a.Aw,a)}},HUa=function(a){a.Qb(0);
a.i.stop();a.Ub(new g.SJ(64))},A9=function(a,b){if(z9(a)&&!a.D){var c=null;
b&&(c={style:a.I.getSubtitlesUserSettings()},g.tc(c,b));a.Tb.cI(a.I.getVideoData(1).videoId,c);a.C=R8(a.Tb).trackData}},B9=function(a,b){var c=a.I.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.I.getVideoData(1);a.Tb.playVideo(c.videoId,b,d,e,c.playerParams,c.Ya,eSa(c));a.Ub(new g.SJ(1))},IUa=function(a,b){if(b){var c=a.I.getOption("captions","tracklist",{PK:1});
c&&c.length?(a.I.setOption("captions","track",b),a.D=!1):(a.I.loadModule("captions"),a.D=!0)}else a.I.setOption("captions","track",{})},z9=function(a){return R8(a.Tb).videoId===a.I.getVideoData(1).videoId},C9=function(){g.V.call(this,{G:"div",
L:"ytp-mdx-popup-dialog",W:{role:"dialog"},U:[{G:"div",L:"ytp-mdx-popup-dialog-inner-content",U:[{G:"div",L:"ytp-mdx-popup-title",va:"You're signed out"},{G:"div",L:"ytp-mdx-popup-description",va:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{G:"div",L:"ytp-mdx-privacy-popup-buttons",U:[{G:"button",Ha:["ytp-button","ytp-mdx-privacy-popup-cancel"],va:"Cancel"},{G:"button",Ha:["ytp-button",
"ytp-mdx-privacy-popup-confirm"],va:"Confirm"}]}]}]});this.i=new g.xL(this,250);this.cancelButton=this.Fa("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.Fa("ytp-mdx-privacy-popup-confirm");g.J(this,this.i);this.T(this.cancelButton,"click",this.u);this.T(this.confirmButton,"click",this.B)},D9=function(a){g.V.call(this,{G:"div",
L:"ytp-remote",U:[{G:"div",L:"ytp-remote-display-status",U:[{G:"div",L:"ytp-remote-display-status-icon",U:[g.Rsa()]},{G:"div",L:"ytp-remote-display-status-text",va:"{{statustext}}"}]}]});this.api=a;this.i=new g.xL(this,250);g.J(this,this.i);this.T(a,"presentingplayerstatechange",this.onStateChange);JUa(this,a.yb())},JUa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
b=g.U(b,128)?g.rI("Error on $RECEIVER_NAME",c):b.Ec()||g.U(b,4)?g.rI("Playing on $RECEIVER_NAME",c):g.rI("Connected to $RECEIVER_NAME",c);a.Sa("statustext",b);a.i.show()}else a.i.hide()},E9=function(a,b){g.OP.call(this,"Play on",0,a,b);
this.I=a;this.jo={};this.T(a,"onMdxReceiversChange",this.D);this.T(a,"presentingplayerstatechange",this.D);this.D()},F9=function(a){g.$M.call(this,a);
this.Ik={key:Y6(),name:"This computer"};this.Zh=null;this.subscriptions=[];this.EF=this.Tb=null;this.jo=[this.Ik];this.Vm=this.Ik;this.ud=new g.SJ(64);this.sL=0;this.vf=-1;this.Jw=!1;this.Hw=this.Ps=null;if(!g.eF(this.player.V())&&!g.fF(this.player.V())){a=this.player;var b=g.DM(a);b&&(b=b.zn())&&(b=new E9(a,b),g.J(this,b));b=new D9(a);g.J(this,b);g.NM(a,b.element,4);this.Ps=new C9;g.J(this,this.Ps);g.NM(a,this.Ps.element,4);this.Jw=!!m9()}},G9=function(a){a.Hw&&(a.player.removeEventListener("presentingplayerstatechange",
a.Hw),a.Hw=null)},KUa=function(a,b,c){a.ud=c;
a.player.ea("presentingplayerstatechange",new g.dI(c,b))},H9=function(a,b){if(b.key!==a.Vm.key)if(b.key===a.Ik.key)s9();
else{var c;(c=!a.player.V().N("mdx_enable_privacy_disclosure_ui"))||(c=((c=g.P("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.P("SESSION_INDEX")&&!g.P("LOGGED_IN")))||a.Jw||!a.Ps);(c?0:g.vF(a.player.V())||g.yF(a.player.V()))&&LUa(a);a.Vm=b;if(!a.player.V().N("disable_mdx_connection_in_mdx_module_for_music_web")||!g.fF(a.player.V())){var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&a.player.V().N("should_clear_video_data_on_player_cued_unstarted"))a=
null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=g.UM(f,l).videoId}else h=[e];f=a.player.getCurrentTime(1);a={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Ya,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=eSa(c))&&(a.locationInfo=c)}j9("Connecting to: "+g.Zh(b));"cast-selector-receiver"==b.key?(l9(a||null),b=a||null,F8()?C8().setLaunchParams(b):A8("setLaunchParams called before ready.")):!a&&v9()&&
i9()==b.key?S6("yt-remote-connection-change",!0):(s9(),l9(a||null),a=h9().Fh(),(b=$6(a,b.key))&&t9(b,1))}}},LUa=function(a){a.player.yb().Ec()?a.player.pauseVideo():(a.Hw=function(b){!a.Jw&&g.fI(b,8)&&(a.player.pauseVideo(),G9(a))},a.player.addEventListener("presentingplayerstatechange",a.Hw));
a.Ps&&a.Ps.td();p9()||(x9=!0)},NSa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},x7={"'":"\\'"},kSa={JY:"atp",B9:"ska",o8:"que",l6:"mus",A9:"sus",z2:"dsp",J8:"seq",O5:"mic",m1:"dpa",YY:"cds",j6:"mlm",j1:"dsdtr"},f7,b7="",ESa=zSa("loadCastFramework")||zSa("loadCastApplicationFramework"),GSa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Qa(k7,g.I);g.k=k7.prototype;g.k.lQ=function(a){this.C=arguments;this.i=!1;this.Lb?this.B=g.Pa()+this.Vf:this.Lb=g.zh(this.D,this.Vf)};
g.k.stop=function(){this.Lb&&(g.D.clearTimeout(this.Lb),this.Lb=null);this.B=null;this.i=!1;this.C=[]};
g.k.pause=function(){++this.u};
g.k.resume=function(){this.u&&(--this.u,!this.u&&this.i&&(this.i=!1,this.J.apply(null,this.C)))};
g.k.xa=function(){this.stop();k7.le.xa.call(this)};
g.k.mQ=function(){this.Lb&&(g.D.clearTimeout(this.Lb),this.Lb=null);this.B?(this.Lb=g.zh(this.D,this.B-g.Pa()),this.B=null):this.u?this.i=!0:(this.i=!1,this.J.apply(null,this.C))};g.w(l7,g.I);g.k=l7.prototype;g.k.XH=function(a){this.B=arguments;this.Lb||this.u?this.i=!0:m7(this)};
g.k.stop=function(){this.Lb&&(g.D.clearTimeout(this.Lb),this.Lb=null,this.i=!1,this.B=null)};
g.k.pause=function(){this.u++};
g.k.resume=function(){this.u--;this.u||!this.i||this.Lb||(this.i=!1,m7(this))};
g.k.xa=function(){g.I.prototype.xa.call(this);this.stop()};n7.prototype.stringify=function(a){return g.D.JSON.stringify(a,void 0)};
n7.prototype.parse=function(a){return g.D.JSON.parse(a,void 0)};var p7=new g.Ue;g.w(ISa,g.xe);g.k=r7.prototype;g.k.Qo=null;g.k.Bm=!1;g.k.It=null;g.k.ZG=null;g.k.Us=null;g.k.vt=null;g.k.Pm=null;g.k.qo=null;g.k.oq=null;g.k.Nf=null;g.k.qB=0;g.k.Jj=null;g.k.nB=null;g.k.Jm=null;g.k.mu=-1;g.k.GN=!0;g.k.jp=!1;g.k.fC=0;g.k.DA=null;var LSa={},u7={};g.k=r7.prototype;g.k.setTimeout=function(a){this.u=a};
g.k.nQ=function(a){a=a.target;var b=this.DA;b&&3==g.Gi(a)?b.XH():this.IO(a)};
g.k.IO=function(a){try{if(a==this.Nf)a:{var b=g.Gi(this.Nf),c=this.Nf.u,d=this.Nf.getStatus();if(g.Qc&&!g.Jc(10)||g.Bg&&!g.Ic("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Li(this.Nf))break a;this.jp||4!=b||7==c||(8==c||0>=d?this.i.tj(3):this.i.tj(2));y7(this);var e=this.Nf.getStatus();this.mu=e;var f=g.Li(this.Nf);if(this.Bm=200==e){4==b&&v7(this);if(this.D){for(a=!0;!this.jp&&this.qB<f.length;){var h=MSa(this,f);if(h==u7){4==b&&(this.Jm=4,q7(15),a=!1);break}else if(h==LSa){this.Jm=4;q7(16);a=!1;
break}else z7(this,h)}4==b&&0==f.length&&(this.Jm=1,q7(17),a=!1);this.Bm=this.Bm&&a;a||(v7(this),w7(this))}else z7(this,f);this.Bm&&!this.jp&&(4==b?this.i.Rx(this):(this.Bm=!1,t7(this)))}else 400==e&&0<f.indexOf("Unknown SID")?(this.Jm=3,q7(13)):(this.Jm=0,q7(14)),v7(this),w7(this)}}catch(l){this.Nf&&g.Li(this.Nf)}finally{}};
g.k.gW=function(a){o7((0,g.E)(this.fW,this,a),0)};
g.k.fW=function(a){this.jp||(y7(this),z7(this,a),t7(this))};
g.k.RM=function(a){o7((0,g.E)(this.eW,this,a),0)};
g.k.eW=function(a){this.jp||(v7(this),this.Bm=a,this.i.Rx(this),this.i.tj(4))};
g.k.cancel=function(){this.jp=!0;v7(this)};
g.k.nW=function(){this.It=null;var a=Date.now();0<=a-this.ZG?(2!=this.vt&&this.i.tj(3),v7(this),this.Jm=2,q7(18),w7(this)):PSa(this,this.ZG-a)};
g.k.getLastError=function(){return this.Jm};g.k=SSa.prototype;g.k.gC=null;g.k.lh=null;g.k.EA=!1;g.k.TN=null;g.k.Ky=null;g.k.CE=null;g.k.hC=null;g.k.Wh=null;g.k.fl=-1;g.k.nu=null;g.k.Ku=null;g.k.connect=function(a){this.hC=a;a=B7(this.i,null,this.hC);q7(3);this.TN=Date.now();var b=this.i.S;null!=b?(this.nu=b[0],(this.Ku=b[1])?(this.Wh=1,TSa(this)):(this.Wh=2,D7(this))):(P6(a,"MODE","init"),this.lh=new r7(this,void 0,void 0,void 0),this.lh.Qo=this.gC,s7(this.lh,a,!1,null,!0),this.Wh=0)};
g.k.eR=function(a){if(a)this.Wh=2,D7(this);else{q7(4);var b=this.i;b.Wj=b.Tm.fl;K7(b,9)}a&&this.tj(2)};
g.k.jD=function(a){return this.i.jD(a)};
g.k.abort=function(){this.lh&&(this.lh.cancel(),this.lh=null);this.fl=-1};
g.k.rf=function(){return!1};
g.k.JM=function(a,b){this.fl=a.mu;if(0==this.Wh)if(b){try{var c=this.u.parse(b)}catch(d){a=this.i;a.Wj=this.fl;K7(a,2);return}this.nu=c[0];this.Ku=c[1]}else a=this.i,a.Wj=this.fl,K7(a,2);else if(2==this.Wh)if(this.EA)q7(7),this.CE=Date.now();else if("11111"==b){if(q7(6),this.EA=!0,this.Ky=Date.now(),a=this.Ky-this.TN,!g.Qc||g.Jc(10)||500>a)this.fl=200,this.lh.cancel(),q7(12),C7(this.i,this,!0)}else q7(8),this.Ky=this.CE=Date.now(),this.EA=!1};
g.k.Rx=function(){this.fl=this.lh.mu;if(this.lh.Bm)0==this.Wh?this.Ku?(this.Wh=1,TSa(this)):(this.Wh=2,D7(this)):2==this.Wh&&((!g.Qc||g.Jc(10)?!this.EA:200>this.CE-this.Ky)?(q7(11),C7(this.i,this,!1)):(q7(12),C7(this.i,this,!0)));else{0==this.Wh?q7(9):2==this.Wh&&q7(10);var a=this.i;this.lh.getLastError();a.Wj=this.fl;K7(a,2)}};
g.k.ix=function(){return this.i.ix()};
g.k.isActive=function(){return this.i.isActive()};
g.k.tj=function(a){this.i.tj(a)};g.k=E7.prototype;g.k.Vj=null;g.k.qv=null;g.k.Vg=null;g.k.He=null;g.k.iC=null;g.k.Ly=null;g.k.bJ=null;g.k.Sx=null;g.k.lw=0;g.k.iT=0;g.k.Of=null;g.k.hn=null;g.k.Al=null;g.k.vp=null;g.k.Tm=null;g.k.lB=null;g.k.As=-1;g.k.rL=-1;g.k.Wj=-1;g.k.Pr=0;g.k.zr=0;g.k.kp=8;g.Qa(VSa,g.xe);g.Qa(WSa,g.xe);g.k=E7.prototype;g.k.connect=function(a,b,c,d,e){q7(0);this.iC=b;this.qv=c||{};d&&void 0!==e&&(this.qv.OSID=d,this.qv.OAID=e);this.J?(o7((0,g.E)(this.xJ,this,a),100),$Sa(this)):this.xJ(a)};
g.k.xJ=function(a){this.Tm=new SSa(this);this.Tm.gC=this.Vj;this.Tm.u=this.D;this.Tm.connect(a)};
g.k.rf=function(){return 0==this.i};
g.k.getState=function(){return this.i};
g.k.PM=function(a){this.hn=null;dTa(this,a)};
g.k.OM=function(){this.Al=null;this.He=new r7(this,this.B,"rpc",this.K);this.He.Qo=this.Vj;this.He.fC=0;var a=this.bJ.clone();g.Zj(a,"RID","rpc");g.Zj(a,"SID",this.B);g.Zj(a,"CI",this.lB?"0":"1");g.Zj(a,"AID",this.As);F7(this,a);if(!g.Qc||g.Jc(10))g.Zj(a,"TYPE","xmlhttp"),s7(this.He,a,!0,this.Sx,!1);else{g.Zj(a,"TYPE","html");var b=this.He,c=!!this.Sx;b.vt=3;b.Pm=O6(a.clone());OSa(b,c)}};
g.k.JM=function(a,b){if(0!=this.i&&(this.He==a||this.Vg==a))if(this.Wj=a.mu,this.Vg==a&&3==this.i)if(7<this.kp){try{var c=this.D.parse(b)}catch(d){c=null}if(Array.isArray(c)&&3==c.length)if(a=c,0==a[0])a:{if(!this.Al){if(this.He)if(this.He.Us+3E3<this.Vg.Us)H7(this),this.He.cancel(),this.He=null;else break a;J7(this);q7(19)}}else this.rL=a[1],0<this.rL-this.As&&37500>a[2]&&this.lB&&0==this.zr&&!this.vp&&(this.vp=o7((0,g.E)(this.KT,this),6E3));else K7(this,11)}else null!=b&&K7(this,11);else if(this.He==
a&&H7(this),!g.$a(b))for(a=this.D.parse(b),b=0;b<a.length;b++)c=a[b],this.As=c[0],c=c[1],2==this.i?"c"==c[0]?(this.B=c[1],this.Sx=c[2],c=c[3],null!=c?this.kp=c:this.kp=6,this.i=3,this.Of&&this.Of.tJ(),this.bJ=B7(this,this.ix()?this.Sx:null,this.iC),eTa(this)):"stop"==c[0]&&K7(this,7):3==this.i&&("stop"==c[0]?K7(this,7):"noop"!=c[0]&&this.Of&&this.Of.sJ(c),this.zr=0)};
g.k.KT=function(){null!=this.vp&&(this.vp=null,this.He.cancel(),this.He=null,J7(this),q7(20))};
g.k.Rx=function(a){if(this.He==a){H7(this);this.He=null;var b=2}else if(this.Vg==a)this.Vg=null,b=1;else return;this.Wj=a.mu;if(0!=this.i)if(a.Bm)if(1==b){b=Date.now()-a.Us;var c=p7;c.dispatchEvent(new VSa(c,a.oq?a.oq.length:0,b,this.Pr));G7(this);this.C.length=0}else eTa(this);else{c=a.getLastError();var d;if(!(d=3==c||7==c||0==c&&0<this.Wj)){if(d=1==b)this.Vg||this.hn||1==this.i||2<=this.Pr?d=!1:(this.hn=o7((0,g.E)(this.PM,this,a),fTa(this,this.Pr)),this.Pr++,d=!0);d=!(d||2==b&&J7(this))}if(d)switch(c){case 1:K7(this,
5);break;case 4:K7(this,10);break;case 3:K7(this,6);break;case 7:K7(this,12);break;default:K7(this,2)}}};
g.k.ER=function(a){if(!g.wb(arguments,this.i))throw Error("Unexpected channel state: "+this.i);};
g.k.qX=function(a){a?q7(2):(q7(1),gTa(this,8))};
g.k.jD=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Ai;a.S=!1;return a};
g.k.isActive=function(){return!!this.Of&&this.Of.isActive(this)};
g.k.tj=function(a){var b=p7;b.dispatchEvent(new WSa(b,a))};
g.k.ix=function(){return!(!g.Qc||g.Jc(10))};
g.k=hTa.prototype;g.k.tJ=function(){};
g.k.sJ=function(){};
g.k.rJ=function(){};
g.k.WC=function(){};
g.k.dK=function(){return{}};
g.k.isActive=function(){return!0};g.k=iTa.prototype;g.k.isEmpty=function(){return 0===this.i.length&&0===this.u.length};
g.k.clear=function(){this.i=[];this.u=[]};
g.k.contains=function(a){return g.wb(this.i,a)||g.wb(this.u,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.lMa)(b,a);0<=c?(g.zb(b,c),b=!0):b=!1;return b||g.Ab(this.u,a)};
g.k.Ip=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Qa(L7,g.I);g.k=L7.prototype;g.k.XV=function(){this.Vf=Math.min(3E5,2*this.Vf);this.B();this.u&&this.start()};
g.k.start=function(){var a=this.Vf+15E3*Math.random();g.Jq(this.i,a);this.u=Date.now()+a};
g.k.stop=function(){this.i.stop();this.u=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Vf=5E3};g.Qa(M7,hTa);g.k=M7.prototype;g.k.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.k.eg=function(a){return this.B.eg(a)};
g.k.ea=function(a,b){return this.B.ea.apply(this.B,arguments)};
g.k.dispose=function(){this.Y||(this.Y=!0,g.ue(this.B),lTa(this),g.ue(this.u),this.u=null,this.ma=function(){return""})};
g.k.isDisposed=function(){return this.Y};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.Z="";this.u.stop();this.D=a||null;this.C=b||0;a=this.ya+"/test";b=this.ya+"/bind";var d=new E7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.Aa),e=this.i;e&&(e.Of=null);d.Of=this;this.i=d;N7(this);if(this.i){d=g.P("ID_TOKEN");var f=this.i.Vj||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.Vj=f}e?(3!=e.getState()&&0==bTa(e)||e.getState(),this.i.connect(a,b,this.J,e.B,e.As)):c?this.i.connect(a,
b,this.J,c.sessionId,c.arrayId):this.i.connect(a,b,this.J)}};
g.k.sendMessage=function(a,b){a={_sc:a};b&&g.tc(a,b);this.u.isActive()||2==(this.i?this.i.getState():0)?this.K.push(a):O7(this)&&(N7(this),aTa(this.i,a))};
g.k.tJ=function(){this.u.reset();this.D=null;this.C=0;if(this.K.length){var a=this.K;this.K=[];for(var b=0,c=a.length;b<c;++b)aTa(this.i,a[b])}this.ea("handlerOpened")};
g.k.rJ=function(a){var b=2==a&&401==this.i.Wj;4==a||b||this.u.start();this.ea("handlerError",a,b)};
g.k.WC=function(a){if(!this.u.isActive())this.ea("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.K.push(d)}};
g.k.dK=function(){var a={v:2};this.Z&&(a.gsessionid=this.Z);0!=this.C&&(a.ui=""+this.C);0!=this.S&&(a.ui=""+this.S);this.D&&g.tc(a,this.D);return a};
g.k.sJ=function(a){"S"==a[0]?this.Z=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),ZSa(this.i)):this.ea("handlerMessage",new jTa(a[0],a[1]))};
g.k.PA=function(a){(this.J.loungeIdToken=a)||this.u.stop();if(this.Ea&&this.i){var b=this.i.Vj||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.Vj=b}};
g.k.UW=function(){this.u.isActive();0==bTa(this.i)&&this.connect(this.D,this.C)};P7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
P7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
P7.prototype.D=function(a){a(Error("request timed out"))};var sTa=Date.now(),S7=null,V7=Array(50),U7=-1,W7=!1;g.Qa(X7,g.R);X7.prototype.Fh=function(){return this.screens};
X7.prototype.contains=function(a){return!!Z6(this.screens,a)};
X7.prototype.get=function(a){return a?$6(this.screens,a):null};
X7.prototype.info=function(a){T7(this.J,a)};g.w(Y7,g.R);g.k=Y7.prototype;g.k.start=function(){!this.i&&isNaN(this.Lb)&&this.bN()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.Lb)||(g.wt(this.Lb),this.Lb=NaN)};
g.k.xa=function(){this.stop();g.R.prototype.xa.call(this)};
g.k.bN=function(){this.Lb=NaN;this.i=g.Ct(Q7(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.K},timeout:5E3,onSuccess:(0,g.E)(this.pQ,this),onError:(0,g.E)(this.oQ,this),onTimeout:(0,g.E)(this.qQ,this)})};
g.k.pQ=function(a,b){this.i=null;a=b.screen||{};a.dialId=this.C;a.name=this.J;b=-1;this.D&&a.shortLivedLoungeToken&&a.shortLivedLoungeToken.value&&a.shortLivedLoungeToken.refreshIntervalMs&&(a.screenIdType="shortLived",a.loungeToken=a.shortLivedLoungeToken.value,b=a.shortLivedLoungeToken.refreshIntervalMs);this.ea("pairingComplete",new U6(a),b)};
g.k.oQ=function(a){this.i=null;a.status&&404==a.status?this.u>=MUa.length?this.ea("pairingFailed",Error("DIAL polling timed out")):(a=MUa[this.u],this.Lb=g.ut((0,g.E)(this.bN,this),a),this.u++):this.ea("pairingFailed",Error("Server error "+a.status))};
g.k.qQ=function(){this.i=null;this.ea("pairingFailed",Error("Server not responding"))};
var MUa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Qa($7,X7);g.k=$7.prototype;g.k.start=function(){Z7(this)&&this.ea("screenChange");!g.Lz("yt-remote-lounge-token-expiration")&&wTa(this);g.wt(this.i);this.i=g.ut((0,g.E)(this.start,this),1E4)};
g.k.add=function(a,b){Z7(this);tTa(this,a);a8(this,!1);this.ea("screenChange");b(a);a.token||wTa(this)};
g.k.remove=function(a,b){var c=Z7(this);vTa(this,a)&&(a8(this,!1),c=!0);b(a);c&&this.ea("screenChange")};
g.k.jB=function(a,b,c,d){var e=Z7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,a8(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.ea("screenChange")};
g.k.xa=function(){g.wt(this.i);$7.le.xa.call(this)};
g.k.aS=function(a){Z7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}a8(this,!b);b&&T7(this.J,"Missed "+b+" lounge tokens.")};
g.k.ZR=function(a){T7(this.J,"Requesting lounge tokens failed: "+a)};g.w(c8,g.R);g.k=c8.prototype;g.k.start=function(){var a=parseInt(g.Lz("yt-remote-fast-check-period")||"0",10);(this.C=g.Pa()-144E5<a?0:a)?f8(this):(this.C=g.Pa()+3E5,g.Kz("yt-remote-fast-check-period",this.C),this.QF())};
g.k.isEmpty=function(){return g.lc(this.i)};
g.k.update=function(){b8("Updating availability on schedule.");var a=this.J(),b=g.Xb(this.i,function(c,d){return c&&!!$6(a,d)},this);
e8(this,b)};
g.k.xa=function(){g.wt(this.B);this.B=NaN;this.u&&(this.u.abort(),this.u=null);g.R.prototype.xa.call(this)};
g.k.QF=function(){g.wt(this.B);this.B=NaN;this.u&&this.u.abort();var a=yTa(this);if(Q6(a)){var b=Q7(this.D,"/pairing/get_screen_availability");this.u=R7(this.D,b,{lounge_token:g.ec(a).join(",")},(0,g.E)(this.EV,this,a),(0,g.E)(this.CV,this))}else e8(this,{}),f8(this)};
g.k.EV=function(a,b){this.u=null;var c=g.ec(yTa(this));if(g.Ob(c,g.ec(a))){b=b.screens||[];c={};for(var d=0,e=b.length;d<e;++d)c[a[b[d].loungeToken]]="online"==b[d].status;e8(this,c);f8(this)}else this.me("Changing Screen set during request."),this.QF()};
g.k.CV=function(a){this.me("Screen availability failed: "+a);this.u=null;f8(this)};
g.k.me=function(a){T7("OnlineScreenService",a)};g.Qa(g8,X7);g.k=g8.prototype;g.k.start=function(){this.u.start();this.i.start();this.screens.length&&(this.ea("screenChange"),this.i.isEmpty()||this.ea("onlineScreenChange"))};
g.k.add=function(a,b,c){this.u.add(a,b,c)};
g.k.remove=function(a,b,c){this.u.remove(a,b,c);this.i.update()};
g.k.jB=function(a,b,c,d){this.u.contains(a)?this.u.jB(a,b,c,d):(a="Updating name of unknown screen: "+a.name,T7(this.J,a),d(Error(a)))};
g.k.Fh=function(a){return a?this.screens:g.Cb(this.screens,g.Ko(this.B,function(b){return!this.contains(b)},this))};
g.k.YH=function(){return g.Ko(this.Fh(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.ZH=function(a,b,c,d,e,f){var h=this;this.info("getDialScreenByPairingCode "+a+" / "+b);var l=new Y7(this.C,a,b,c,d);l.subscribe("pairingComplete",function(m,n){g.ue(l);e(h8(h,m),n)});
l.subscribe("pairingFailed",function(m){g.ue(l);f(m)});
l.start();return(0,g.E)(l.stop,l)};
g.k.rQ=function(a,b,c,d){g.Ct(Q7(this.C,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.E)(function(e,f){e=new U6(f.screen||{});if(!e.name||CTa(this,e.name)){a:{f=e.name;for(var h=2,l=b(f,h);CTa(this,l);){h++;if(20<h)break a;l=b(f,h)}f=l}e.name=f}c(h8(this,e))},this),
onError:(0,g.E)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.E)(function(){d(Error("pairing request timed out."))},this)})};
g.k.xa=function(){g.ue(this.u);g.ue(this.i);g8.le.xa.call(this)};
g.k.jS=function(){ETa(this);this.ea("screenChange");this.i.update()};
g8.prototype.dispose=g8.prototype.dispose;g.Qa(j8,g.R);g.k=j8.prototype;g.k.getScreen=function(){return this.C};
g.k.zg=function(a){this.isDisposed()||(a&&(l8(this,""+a),this.ea("sessionFailed")),this.C=null,this.ea("sessionScreen",null))};
g.k.info=function(a){T7(this.Ea,a)};
g.k.aI=function(){return null};
g.k.fG=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.E)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.E)(function(){l8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.xa=function(){this.fG("");j8.le.xa.call(this)};g.w(m8,j8);g.k=m8.prototype;g.k.eG=function(a){if(this.u){if(this.u==a)return;l8(this,"Overriding cast session with new session object");NTa(this);this.ya=!1;this.Z="unknown";this.u.removeUpdateListener(this.ma);this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa)}this.u=a;this.u.addUpdateListener(this.ma);this.u.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa);JTa(this,"getMdxSessionStatus")};
g.k.Bs=function(a){this.info("launchWithParams no-op for Cast: "+g.Zh(a))};
g.k.stop=function(){this.u?this.u.stop((0,g.E)(function(){this.zg()},this),(0,g.E)(function(){this.zg(Error("Failed to stop receiver app."))},this)):this.zg(Error("Stopping cast device without session."))};
g.k.fG=function(){};
g.k.xa=function(){this.info("disposeInternal");NTa(this);this.u&&(this.u.removeUpdateListener(this.ma),this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa));this.u=null;j8.prototype.xa.call(this)};
g.k.rW=function(a,b){if(!this.isDisposed())if(b)if(b=R6(b),g.La(b))switch(a=""+b.type,b=b.data||{},this.info("onYoutubeMessage_: "+a+" "+g.Zh(b)),a){case "mdxSessionStatus":HTa(this,b);break;case "loungeToken":KTa(this,b);break;default:l8(this,"Unknown youtube message: "+a)}else l8(this,"Unable to parse message.");else l8(this,"No data in message.")};
g.k.rK=function(a,b,c,d){g.wt(this.S);this.S=0;BTa(this.B,this.i.label,a,this.i.friendlyName,(0,g.E)(function(e){e?b(e):0<=d?(l8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.S=g.ut((0,g.E)(this.rK,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.aI=function(){return this.u};
g.k.sQ=function(a){this.isDisposed()||a||(l8(this,"Cast session died."),this.zg())};g.w(p8,j8);g.k=p8.prototype;g.k.eG=function(a){this.u=a;this.u.addUpdateListener(this.Ka)};
g.k.Bs=function(a){this.Ja=a;this.Y()};
g.k.stop=function(){UTa(this);this.u?this.u.stop((0,g.E)(this.zg,this,null),(0,g.E)(this.zg,this,"Failed to stop DIAL device.")):this.zg()};
g.k.xa=function(){UTa(this);this.u&&this.u.removeUpdateListener(this.Ka);this.u=null;j8.prototype.xa.call(this)};
g.k.tQ=function(a){this.isDisposed()||a||(l8(this,"DIAL session died."),this.D(),this.D=g.Ha,this.zg())};g.w(t8,j8);t8.prototype.stop=function(){this.zg()};
t8.prototype.eG=function(){};
t8.prototype.Bs=function(){g.wt(this.u);this.u=NaN;var a=$6(this.B.Fh(),this.i.label);a?k8(this,a):this.zg(Error("No such screen"))};
t8.prototype.xa=function(){g.wt(this.u);this.u=NaN;j8.prototype.xa.call(this)};g.w(u8,g.R);g.k=u8.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.S,[chrome.cast.Capability.AUDIO_OUT]);this.Z||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED;a=a||this.J?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;var e=(0,g.E)(this.nV,this);c=new chrome.cast.ApiConfig(c,(0,g.E)(this.KM,this),e,d,a);c.customDialLaunchCallback=(0,g.E)(this.iU,this);
chrome.cast.initialize(c,(0,g.E)(function(){this.isDisposed()||(chrome.cast.addReceiverActionListener(this.D),pTa(),this.u.subscribe("onlineScreenChange",(0,g.E)(this.bI,this)),this.B=XTa(this),chrome.cast.setCustomReceivers(this.B,g.Ha,(0,g.E)(function(f){this.me("Failed to set initial custom receivers: "+g.Zh(f))},this)),this.ea("yt-remote-cast2-availability-change",w8(this)),b(!0))},this),(0,g.E)(function(f){this.me("Failed to initialize API: "+g.Zh(f));
b(!1)},this))};
g.k.ZW=function(a,b){v8("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)v8("Unsetting old screen status: "+this.i.i.friendlyName),x8(this,null)}if(a&&b){if(!this.i){c=$6(this.u.Fh(),a);if(!c){v8("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){v8("setConnectedScreenStatus: Screen with id type to be short lived.");return}a=VTa(this,c);a||(v8("setConnectedScreenStatus: Connected receiver not custom..."),a=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),a.receiverType=chrome.cast.ReceiverType.CUSTOM,this.B.push(a),chrome.cast.setCustomReceivers(this.B,g.Ha,(0,g.E)(function(d){this.me("Failed to set initial custom receivers: "+g.Zh(d))},this)));
v8("setConnectedScreenStatus: new active receiver: "+a.friendlyName);x8(this,new t8(this.u,a),!0)}this.i.fG(b)}else v8("setConnectedScreenStatus: no screen.")};
g.k.aX=function(a){this.isDisposed()?this.me("Setting connection data on disposed cast v2"):this.i?this.i.Bs(a):this.me("Setting connection data without a session")};
g.k.vQ=function(){this.isDisposed()?this.me("Stopping session on disposed cast v2"):this.i?(this.i.stop(),x8(this,null)):v8("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.E)(this.KM,this),(0,g.E)(this.HV,this))};
g.k.xa=function(){this.u.unsubscribe("onlineScreenChange",(0,g.E)(this.bI,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.D);var a=mTa,b=g.Ga("yt.mdx.remote.debug.handlers_");g.Ab(b||[],a);g.ue(this.i);g.R.prototype.xa.call(this)};
g.k.me=function(a){T7("Controller",a)};
g.k.MM=function(a,b){this.i==a&&(b||x8(this,null),this.ea("yt-remote-cast2-session-change",b))};
g.k.kV=function(a,b){if(!this.isDisposed())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),v8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)v8("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{v8("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.ea("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:x8(this,
new t8(this.u,a));break;case chrome.cast.ReceiverType.DIAL:x8(this,new p8(this.u,a,this.C,this.config_));break;case chrome.cast.ReceiverType.CAST:x8(this,new m8(this.u,a,this.config_));break;default:this.me("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.me("Stopping receiver w/o session: "+a.friendlyName)}else this.me("onReceiverAction_ called without receiver.")};
g.k.iU=function(a){if(this.isDisposed())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.me("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.me("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return v8("Reselecting dial screen."),
this.ea("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.me('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);x8(this,new p8(this.u,b,this.C,this.config_))}b=this.i;b.S=a;b.S.appState==chrome.cast.DialAppState.RUNNING?(a=b.S.extraData||{},c=a.screenId||null,q8(b)&&a.loungeToken?a.loungeTokenRefreshIntervalMs?a=RTa(b,{name:b.i.friendlyName,screenId:a.screenId,loungeToken:a.loungeToken,dialId:b.S.receiver.label,
screenIdType:"shortLived"},a.loungeTokenRefreshIntervalMs):(g.Gs(Error("No loungeTokenRefreshIntervalMs presents in additionalData: "+JSON.stringify(a)+".")),a=STa(b,c)):a=STa(b,c)):a=s8(b);return a};
g.k.KM=function(a){var b=this;if(!this.isDisposed()&&!this.J){v8("New cast session ID: "+a.sessionId);var c=a.receiver;if(c.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(c.receiverType==chrome.cast.ReceiverType.CAST)v8("Got resumed cast session before resumed mdx connection."),c.friendlyName=chrome.cast.unescape(c.friendlyName),x8(this,new m8(this.u,c,this.config_),!0);else{this.me("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var d=this.i.i,e=$6(this.u.Fh(),
d.label);e&&V6(e,c.label)&&d.receiverType!=chrome.cast.ReceiverType.CAST&&c.receiverType==chrome.cast.ReceiverType.CAST&&(v8("onSessionEstablished_: manual to cast session change "+c.friendlyName),g.ue(this.i),this.i=new m8(this.u,c,this.config_),this.i.subscribe("sessionScreen",(0,g.E)(this.MM,this,this.i)),this.i.subscribe("sessionFailed",function(){return WTa(b,b.i)}),this.i.Bs(null));
this.i.eG(a)}}};
g.k.uQ=function(){return this.i?this.i.aI():null};
g.k.HV=function(a){this.isDisposed()||(this.me("Failed to estabilish a session: "+g.Zh(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&x8(this,null),this.ea("yt-remote-cast2-session-failed"))};
g.k.nV=function(a){v8("Receiver availability updated: "+a);if(!this.isDisposed()){var b=w8(this);this.K=a==chrome.cast.ReceiverAvailability.AVAILABLE;w8(this)!=b&&this.ea("yt-remote-cast2-availability-change",w8(this))}};
g.k.bI=function(){this.isDisposed()||(this.B=XTa(this),v8("Updating custom receivers: "+g.Zh(this.B)),chrome.cast.setCustomReceivers(this.B,g.Ha,(0,g.E)(function(){this.me("Failed to set custom receivers.")},this)),this.ea("yt-remote-cast2-availability-change",w8(this)))};
u8.prototype.setLaunchParams=u8.prototype.aX;u8.prototype.setConnectedScreenStatus=u8.prototype.ZW;u8.prototype.stopSession=u8.prototype.vQ;u8.prototype.getCastSession=u8.prototype.uQ;u8.prototype.requestSession=u8.prototype.requestSession;u8.prototype.init=u8.prototype.init;u8.prototype.dispose=u8.prototype.dispose;var D8=[];g.k=I8.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";J8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.trackData=a.trackData,this.Ak=a.hasPrevious,this.hasNext=a.hasNext,this.K=a.playerTime,this.J=a.playerTimeAt,this.C=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.S=a.loadedTime,this.B=a.liveIngestionTime,this.u=
!isNaN(this.B))};
g.k.Ec=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.Ej=function(a){this.D=isNaN(a)?0:a};
g.k.getDuration=function(){return this.u?this.D+K8(this):this.D};
g.k.clone=function(){return new I8(O8(this))};g.w(Q8,g.R);g.k=Q8.prototype;g.k.getState=function(){return this.B};
g.k.play=function(){S8(this)?(this.i?this.i.play(null,g.Ha,X8(this,"play")):W8(this,"play"),V8(this,1,M8(R8(this))),this.ea("remotePlayerChange")):T8(this,this.play)};
g.k.pause=function(){S8(this)?(this.i?this.i.pause(null,g.Ha,X8(this,"pause")):W8(this,"pause"),V8(this,2,M8(R8(this))),this.ea("remotePlayerChange")):T8(this,this.pause)};
g.k.seekTo=function(a){if(S8(this)){if(this.i){var b=R8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.Ec()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ha,X8(this,"seekTo",{newTime:a}))}else W8(this,"seekTo",{newTime:a});V8(this,3,a);this.ea("remotePlayerChange")}else T8(this,g.Oa(this.seekTo,a))};
g.k.stop=function(){if(S8(this)){this.i?this.i.stop(null,g.Ha,X8(this,"stopVideo")):W8(this,"stopVideo");var a=R8(this);a.index=-1;a.videoId="";J8(a);U8(this,a);this.ea("remotePlayerChange")}else T8(this,this.stop)};
g.k.setVolume=function(a,b){if(S8(this)){var c=R8(this);if(this.u){if(c.volume!=a){var d=Math.round(a)/100;this.u.setReceiverVolumeLevel(d,(0,g.E)(function(){T7("CP","set receiver volume: "+d)},this),(0,g.E)(function(){this.me("failed to set receiver volume.")},this))}c.muted!=b&&this.u.setReceiverMuted(b,(0,g.E)(function(){T7("CP","set receiver muted: "+b)},this),(0,g.E)(function(){this.me("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);W8(this,"setVolume",e)}c.muted=b;c.volume=a;U8(this,c)}else T8(this,g.Oa(this.setVolume,a,b))};
g.k.cI=function(a,b){if(S8(this)){var c=R8(this);a={videoId:a};b&&(c.trackData={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},a.style=g.Zh(b.style),g.tc(a,c.trackData));W8(this,"setSubtitlesTrack",a);U8(this,c)}else T8(this,g.Oa(this.cI,a,b))};
g.k.setAudioTrack=function(a,b){S8(this)?(b=b.getLanguageInfo().getId(),W8(this,"setAudioTrack",{videoId:a,audioTrackId:b}),a=R8(this),a.audioTrackId=b,U8(this,a)):T8(this,g.Oa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){d=void 0===d?null:d;e=void 0===e?null:e;f=void 0===f?null:f;h=void 0===h?null:h;var l=R8(this),m={videoId:a};void 0!==c&&(m.currentIndex=c);N8(l,a,c||0);void 0!==b&&(L8(l,b),m.currentTime=b);d&&(m.listId=d);e&&(m.playerParams=e);f&&(m.clickTrackingParams=f);h&&(m.locationInfo=g.Zh(h));W8(this,"setPlaylist",m);d||U8(this,l)};
g.k.wA=function(a,b){if(S8(this)){if(a&&b){var c=R8(this);N8(c,a,b);U8(this,c)}W8(this,"previous")}else T8(this,g.Oa(this.wA,a,b))};
g.k.nextVideo=function(a,b){if(S8(this)){if(a&&b){var c=R8(this);N8(c,a,b);U8(this,c)}W8(this,"next")}else T8(this,g.Oa(this.nextVideo,a,b))};
g.k.Cr=function(){if(S8(this)){W8(this,"clearPlaylist");var a=R8(this);a.reset();U8(this,a);this.ea("remotePlayerChange")}else T8(this,this.Cr)};
g.k.NJ=function(){S8(this)?W8(this,"dismissAutoplay"):T8(this,this.NJ)};
g.k.dispose=function(){if(3!=this.B){var a=this.B;this.B=3;this.ea("proxyStateChange",a,this.B)}g.R.prototype.dispose.call(this)};
g.k.xa=function(){iUa(this);this.C=null;this.D.clear();P8(this,null);g.R.prototype.xa.call(this)};
g.k.gG=function(a){if((a!=this.B||2==a)&&3!=this.B&&0!=a){var b=this.B;this.B=a;this.ea("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)b=a=this.D,0===b.i.length&&(b.i=b.u,b.i.reverse(),b.u=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.iV=function(a,b){this.ea(a,b)};
g.k.RT=function(a){if(!a)this.ww(null),P8(this,null);else if(this.u.receiver.volume){a=this.u.receiver.volume;var b=R8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)T7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,U8(this,b)}};
g.k.ww=function(a){T7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.S);if(this.i=a)this.i.addUpdateListener(this.S),jUa(this),this.ea("remotePlayerChange")};
g.k.QT=function(a){a?(jUa(this),this.ea("remotePlayerChange")):this.ww(null)};
g.k.BG=function(){W8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.aU=function(){var a=fUa();a&&P8(this,a)};
g.k.me=function(a){T7("CP",a)};g.w(Y8,g.R);g.k=Y8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.videoIds,f=b.playerParams,h=b.clickTrackingParams,l=b.index,m={videoId:d},n=b.currentTime,p=b.locationInfo;b=b.loopMode;void 0!==n&&(m.currentTime=5>=n?0:n);f&&(m.playerParams=f);p&&(m.locationInfo=p);h&&(m.clickTrackingParams=h);c&&(m.listId=c);e&&0<e.length&&(m.videoIds=e.join(","));void 0!==l&&(m.currentIndex=l);this.Ea&&(m.loopMode=b||"LOOP_MODE_OFF");c&&(this.hc.listId=c);this.hc.videoId=d;this.hc.index=l||0;this.hc.state=3;L8(this.hc,
n);this.C="UNSUPPORTED";c=this.Ea?"setInitialState":"setPlaylist";Z8("Connecting with "+c+" and params: "+g.Zh(m));this.i.connect({method:c,params:g.Zh(m)},a,sSa())}else Z8("Connecting without params"),this.i.connect({},a,sSa());mUa(this)};
g.k.PA=function(a){this.i.PA(a)};
g.k.dispose=function(){this.isDisposed()||(g.Fa("yt.mdx.remote.remoteClient_",null,void 0),this.ea("beforeDispose"),$8(this,3));g.R.prototype.dispose.call(this)};
g.k.xa=function(){a9(this);c9(this);b9(this);g.wt(this.K);this.K=NaN;g.wt(this.S);this.S=NaN;this.B=null;g.Bu(this.Z);this.Z.length=0;this.i.dispose();g.R.prototype.xa.call(this);this.C=this.J=this.u=this.hc=this.i=null};
g.k.VR=function(){this.Lr(2)};
g.k.VT=function(){Z8("Channel opened");this.ya&&(this.ya=!1,b9(this),this.ma=g.ut((0,g.E)(function(){Z8("Timing out waiting for a screen.");this.Lr(1)},this),15E3));
wSa(kTa(this.i),this.Ja)};
g.k.ST=function(){Z8("Channel closed");isNaN(this.D)?e7(!0):e7();this.dispose()};
g.k.TT=function(a,b){e7();isNaN(this.Iv())?(b&&"shortLived"==this.Aa&&this.ea("browserChannelAuthError",a),Z8("Channel error: "+a+" without reconnection"),this.dispose()):(this.ya=!0,Z8("Channel error: "+a+" with reconnection in "+this.Iv()+" ms"),$8(this,2))};
g.k.cL=function(a){if(!this.u||0===this.u.length)return!1;for(var b=g.r(this.u),c=b.next();!c.done;c=b.next())if(!c.value.capabilities.has(a))return!1;return!0};
g.k.UT=function(a){a.params?Z8("Received: action="+a.action+", params="+g.Zh(a.params)):Z8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=R6(a.params.devices);this.u=g.ym(a,function(c){return new T6(c)});
a=!!g.tb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
pUa(this,a);a=this.cL("mlm");this.ea("multiStateLoopEnabled",a);break;case "loungeScreenDisconnected":g.Bb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
pUa(this,!1);break;case "remoteConnected":var b=new T6(R6(a.params.device));g.tb(this.u,function(c){return b?c.id==b.id:!1})||fSa(this.u,b);
break;case "remoteDisconnected":b=new T6(R6(a.params.device));g.Bb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":rUa(this,a);break;case "nowPlaying":tUa(this,a);break;case "onStateChange":sUa(this,a);break;case "onAdStateChange":uUa(this,a);break;case "onVolumeChanged":vUa(this,a);break;case "onSubtitlesTrackChanged":qUa(this,a);break;case "nowAutoplaying":wUa(this,a);break;case "autoplayDismissed":this.ea("autoplayDismissed");break;case "autoplayUpNext":this.J=a.params.videoId||null;this.ea("autoplayUpNext",this.J);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.ea("autoplayModeChange",this.C);"DISABLED"==this.C&&this.ea("autoplayDismissed");break;case "onHasPreviousNextChanged":xUa(this,a);break;case "requestAssistedSignIn":this.ea("assistedSignInRequested",a.params.authCode);break;case "onLoopModeChanged":this.ea("loopModeChange",a.params.loopMode);break;default:Z8("Unrecognized action: "+a.action)}};
g.k.NW=function(){if(this.B){var a=this.B;this.B=null;this.hc.videoId!=a&&d9(this,"getNowPlaying")}};
g.k.SR=function(){var a=3;this.isDisposed()||(a=0,isNaN(this.Iv())?O7(this.i)&&isNaN(this.D)&&(a=1):a=2);return a};
g.k.Lr=function(a){Z8("Disconnecting with "+a);g.Fa("yt.mdx.remote.remoteClient_",null,void 0);a9(this);this.ea("beforeDisconnect",a);1==a&&e7();lTa(this.i,a);this.dispose()};
g.k.QR=function(){var a=this.hc;this.B&&(a=this.hc.clone(),N8(a,this.B,a.index));return O8(a)};
g.k.bX=function(a){var b=new I8(a);b.videoId&&b.videoId!=this.hc.videoId&&(this.B=b.videoId,g.wt(this.K),this.K=g.ut((0,g.E)(this.NW,this),5E3));var c=[];this.hc.listId==b.listId&&this.hc.videoId==b.videoId&&this.hc.index==b.index||c.push("remoteQueueChange");this.hc.playerState==b.playerState&&this.hc.volume==b.volume&&this.hc.muted==b.muted&&M8(this.hc)==M8(b)&&g.Zh(this.hc.trackData)==g.Zh(b.trackData)||c.push("remotePlayerChange");this.hc.reset(a);g.Qb(c,function(d){this.ea(d)},this)};
g.k.qK=function(){var a=this.i.J.id,b=g.tb(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Iv=function(){var a=this.i;return a.u.isActive()?a.u.u-Date.now():NaN};
g.k.NR=function(){return this.C||"UNSUPPORTED"};
g.k.OR=function(){return this.J||""};
g.k.wQ=function(){if(!isNaN(this.Iv())){var a=this.i.u;g.Kq(a.i);a.start()}};
g.k.YW=function(a,b){d9(this,a,b);oUa(this)};
g.k.dI=function(){var a=g.Ot("SID","")||"",b=g.Ot("SAPISID","")||"",c=g.Ot("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.Mc(g.Wa(a),2);b=g.Mc(g.Wa(b),2);c=g.Mc(g.Wa(c),2);return g.Mc(g.Wa(a+","+b+","+c),2)};
Y8.prototype.subscribe=Y8.prototype.subscribe;Y8.prototype.unsubscribeByKey=Y8.prototype.eg;Y8.prototype.getProxyState=Y8.prototype.SR;Y8.prototype.disconnect=Y8.prototype.Lr;Y8.prototype.getPlayerContextData=Y8.prototype.QR;Y8.prototype.setPlayerContextData=Y8.prototype.bX;Y8.prototype.getOtherConnectedRemoteId=Y8.prototype.qK;Y8.prototype.getReconnectTimeout=Y8.prototype.Iv;Y8.prototype.getAutoplayMode=Y8.prototype.NR;Y8.prototype.getAutoplayVideoId=Y8.prototype.OR;Y8.prototype.reconnect=Y8.prototype.wQ;
Y8.prototype.sendMessage=Y8.prototype.YW;Y8.prototype.getXsrfToken=Y8.prototype.dI;Y8.prototype.isCapabilitySupportedOnConnectedDevices=Y8.prototype.cL;g.w(e9,X7);g.k=e9.prototype;g.k.Fh=function(a){return this.Qe.$_gs(a)};
g.k.contains=function(a){return!!this.Qe.$_c(a)};
g.k.get=function(a){return this.Qe.$_g(a)};
g.k.start=function(){this.Qe.$_st()};
g.k.add=function(a,b,c){this.Qe.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Qe.$_r(a,b,c)};
g.k.jB=function(a,b,c,d){this.Qe.$_un(a,b,c,d)};
g.k.xa=function(){for(var a=0,b=this.i.length;a<b;++a)this.Qe.$_ubk(this.i[a]);this.i.length=0;this.Qe=null;X7.prototype.xa.call(this)};
g.k.xQ=function(){this.ea("screenChange")};
g.k.PU=function(){this.ea("onlineScreenChange")};
g8.prototype.$_st=g8.prototype.start;g8.prototype.$_gspc=g8.prototype.rQ;g8.prototype.$_gsppc=g8.prototype.ZH;g8.prototype.$_c=g8.prototype.contains;g8.prototype.$_g=g8.prototype.get;g8.prototype.$_a=g8.prototype.add;g8.prototype.$_un=g8.prototype.jB;g8.prototype.$_r=g8.prototype.remove;g8.prototype.$_gs=g8.prototype.Fh;g8.prototype.$_gos=g8.prototype.YH;g8.prototype.$_s=g8.prototype.subscribe;g8.prototype.$_ubk=g8.prototype.eg;var r9=null,x9=!1,f9=null,g9=null,w9=null,k9=[];g.w(y9,g.I);g.k=y9.prototype;g.k.xa=function(){g.I.prototype.xa.call(this);this.i.stop();this.B.stop();this.S.stop();this.ma();var a=this.Tb;a.unsubscribe("proxyStateChange",this.IM,this);a.unsubscribe("remotePlayerChange",this.Aw,this);a.unsubscribe("remoteQueueChange",this.iA,this);a.unsubscribe("previousNextChange",this.FM,this);a.unsubscribe("nowAutoplaying",this.zM,this);a.unsubscribe("autoplayDismissed",this.cM,this);this.Tb=this.u=null};
g.k.lj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Tb.B)if(z9(this)){if(!R8(this.Tb).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":R8(this.Tb).Ec()?this.Tb.pause():this.Tb.play();break;case "control_play":this.Tb.play();break;case "control_pause":this.Tb.pause();break;case "control_seek":this.K.XH(c[0],c[1]);break;case "control_subtitles_set_track":A9(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.I.getCurrentTime();B9(this,0===c?void 0:c);break;case "control_seek":B9(this,c[0]);break;case "control_subtitles_set_track":A9(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.OT=function(a){this.S.lQ(a)};
g.k.GX=function(a){this.lj("control_subtitles_set_track",g.lc(a)?null:a)};
g.k.YN=function(){var a=this.I.getOption("captions","track");g.lc(a)||A9(this,a)};
g.k.Qb=function(a){this.u.Qb(a,this.I.getVideoData().lengthSeconds)};
g.k.AU=function(){g.lc(this.C)||IUa(this,this.C);this.D=!1};
g.k.IM=function(a,b){this.B.stop();2===b&&this.SN()};
g.k.Aw=function(){if(z9(this)){this.i.stop();var a=R8(this.Tb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.vf=1;break;case 1082:case 1083:this.u.vf=0;break;default:this.u.vf=-1}switch(a.playerState){case 1081:case 1:this.Ub(new g.SJ(8));this.RN();break;case 1085:case 3:this.Ub(new g.SJ(9));break;case 1083:case 0:this.Ub(new g.SJ(2));this.K.stop();this.Qb(this.I.getVideoData().lengthSeconds);break;case 1084:this.Ub(new g.SJ(4));break;case 2:this.Ub(new g.SJ(4));this.Qb(M8(a));
break;case -1:this.Ub(new g.SJ(64));break;case -1E3:this.Ub(new g.SJ(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=R8(this.Tb).trackData;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.C=a,IUa(this,a));a=R8(this.Tb);-1===a.volume||Math.round(this.I.getVolume())===a.volume&&this.I.isMuted()===a.muted||this.Z.isActive()||this.AO()}else HUa(this)};
g.k.FM=function(){this.I.ea("mdxpreviousnextchange")};
g.k.iA=function(){z9(this)||HUa(this)};
g.k.zM=function(a){isNaN(a)||this.I.ea("mdxnowautoplaying",a)};
g.k.cM=function(){this.I.ea("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){z9(this)&&this.Tb.setAudioTrack(this.I.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===R8(this.Tb).playerState?B9(this,a):b&&this.Tb.seekTo(a)};
g.k.AO=function(){var a=this;if(z9(this)){var b=R8(this.Tb);this.events.jc(this.Y);b.muted?this.I.mute():this.I.unMute();this.I.setVolume(b.volume);this.Y=this.events.T(this.I,"onVolumeChange",function(c){GUa(a,c)})}};
g.k.RN=function(){this.i.stop();if(!this.Tb.isDisposed()){var a=R8(this.Tb);a.Ec()&&this.Ub(new g.SJ(8));this.Qb(M8(a));this.i.start()}};
g.k.SN=function(){this.B.stop();this.i.stop();var a=this.Tb.C.getReconnectTimeout();2==this.Tb.B&&!isNaN(a)&&this.B.start()};
g.k.Ub=function(a){this.B.stop();var b=this.J;if(!g.XJ(b,a)){var c=g.U(a,2);c!==g.U(this.J,2)&&this.I.Zs(c);this.J=a;KUa(this.u,b,a)}};g.w(C9,g.V);C9.prototype.td=function(){this.i.show()};
C9.prototype.Eb=function(){this.i.hide()};
C9.prototype.u=function(){S6("mdx-privacy-popup-cancel");this.Eb()};
C9.prototype.B=function(){S6("mdx-privacy-popup-confirm");this.Eb()};g.w(D9,g.V);D9.prototype.onStateChange=function(a){JUa(this,a.state)};g.w(E9,g.OP);E9.prototype.D=function(){var a=this.I.getOption("remote","receivers");a&&1<a.length&&!this.I.getOption("remote","quickCast")?(this.jo=g.Rb(a,this.i,this),g.PP(this,g.ym(a,this.i)),a=this.I.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.Vh(a),this.enable(!0)):this.enable(!1)};
E9.prototype.i=function(a){return a.key};
E9.prototype.bj=function(a){return"cast-selector-receiver"===a?"Cast...":this.jo[a].name};
E9.prototype.Cf=function(a){g.OP.prototype.Cf.call(this,a);this.I.setOption("remote","currentReceiver",this.jo[a]);this.Bb.Eb()};g.w(F9,g.$M);g.k=F9.prototype;
g.k.create=function(){var a=this.player.V(),b=g.cF(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:a.N("mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:a.N("enable_dial_short_lived_lounge_token"),enableCastLoungeToken:a.N("enable_cast_short_lived_lounge_token")};BUa(b,a);this.subscriptions.push(g.hv("yt-remote-before-disconnect",this.NT,this));this.subscriptions.push(g.hv("yt-remote-connection-change",this.oV,this));this.subscriptions.push(g.hv("yt-remote-receiver-availability-change",this.HM,
this));this.subscriptions.push(g.hv("yt-remote-auto-connect",this.mV,this));this.subscriptions.push(g.hv("yt-remote-receiver-resumed",this.lV,this));this.subscriptions.push(g.hv("mdx-privacy-popup-confirm",this.BW,this));this.subscriptions.push(g.hv("mdx-privacy-popup-cancel",this.zW,this));this.HM()};
g.k.load=function(){this.player.cancelPlayback();g.$M.prototype.load.call(this);this.Zh=new y9(this,this.player,this.Tb);var a=(a=FUa())?a.currentTime:0;var b=v9()?new Q8(p9(),void 0):null;0==a&&b&&(a=M8(R8(b)));0!==a&&this.Qb(a);KUa(this,this.ud,this.ud);this.player.Tk(6)};
g.k.unload=function(){this.player.ea("mdxautoplaycanceled");this.Vm=this.Ik;g.ve(this.Zh,this.Tb);this.Tb=this.Zh=null;g.$M.prototype.unload.call(this);this.player.Tk(5);G9(this)};
g.k.xa=function(){g.iv(this.subscriptions);g.$M.prototype.xa.call(this)};
g.k.Kk=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.Zh.lj.apply(this.Zh,[a].concat(g.v(c)))};
g.k.getAdState=function(){return this.vf};
g.k.Ak=function(){return this.Tb?R8(this.Tb).Ak:!1};
g.k.hasNext=function(){return this.Tb?R8(this.Tb).hasNext:!1};
g.k.Qb=function(a,b){this.sL=a||0;this.player.ea("progresssync",a,b);this.player.Oa("onVideoProgress",a||0)};
g.k.getCurrentTime=function(){return this.sL};
g.k.getProgressState=function(){var a=R8(this.Tb),b=this.player.getVideoData();return{airingStart:0,airingEnd:0,allowSeeking:this.player.V().N("web_player_mdx_allow_seeking_change_killswitch")?this.player.sf():!a.isAdPlaying()&&this.player.sf(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.B+K8(a):a.B,isAtLiveHead:1>=(a.u?a.i+K8(a):a.i)-this.getCurrentTime(),loaded:a.S,seekableEnd:a.u?a.i+K8(a):a.i,seekableStart:0<
a.C?a.C+K8(a):a.C}};
g.k.nextVideo=function(){this.Tb&&this.Tb.nextVideo()};
g.k.wA=function(){this.Tb&&this.Tb.wA()};
g.k.NT=function(a){1===a&&(this.EF=this.Tb?R8(this.Tb):null)};
g.k.oV=function(){var a=v9()?new Q8(p9(),void 0):null;if(a){var b=this.Vm;this.loaded&&this.unload();this.Tb=a;this.EF=null;b.key!==this.Ik.key&&(this.Vm=b,this.load())}else g.ue(this.Tb),this.Tb=null,this.loaded&&(this.unload(),(a=this.EF)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,M8(a)));this.player.ea("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.HM=function(){var a=[this.Ik],b=a.concat,c=CUa();E8()&&g.Lz("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.jo=b.call(a,c);a=q9()||this.Ik;H9(this,a);this.player.Oa("onMdxReceiversChange")};
g.k.mV=function(){var a=q9();H9(this,a)};
g.k.lV=function(){this.Vm=q9()};
g.k.BW=function(){this.Jw=!0;G9(this);x9=!1;r9&&t9(r9,1);r9=null};
g.k.zW=function(){this.Jw=!1;G9(this);H9(this,this.Ik);this.Vm=this.Ik;x9=!1;r9=null;this.player.playVideo()};
g.k.kf=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.jo;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?G8():H9(this,b)),this.loaded?this.Vm:this.Ik;case "quickCast":return 2===this.jo.length&&"cast-selector-receiver"===this.jo[1].key?(b&&G8(),!0):!1}};
g.k.BG=function(){this.Tb.BG()};
g.k.Ii=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.ZM("remote",F9);})(_yt_player);
